// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface check
var _ pluginapi.PluginTool = (*get_weatherTool)(nil)

// GetWeatherParams represents the parameters for this plugin
type GetWeatherParams struct {
	Location string `json:"location"` // Location to get weather for
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *get_weatherTool) Call(ctx context.Context, args string) (string, error) {
	var params GetWeatherParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.Location == "" {
		return "", fmt.Errorf("required field 'location' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
