// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/oriagent/ori-pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*GetWeatherTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool       = (*GetWeatherTool)(nil)
	_ pluginapi.MetadataProvider    = (*GetWeatherTool)(nil)
	_ pluginapi.PluginCompatibility = (*GetWeatherTool)(nil)
)

//go:embed plugin.yaml
var configYAML string

// Params represents the parameters for this plugin
type Params struct {
	Location string `json:"location"` // Location to get weather for
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *GetWeatherTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params Params

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method
	return t.Execute(ctx, &params)
}
