# GoReleaser Configuration for Ori Agent
# Automates multi-platform releases with installers for macOS, Windows, and Linux
# See: https://goreleaser.com

version: 2

# Project metadata
project_name: ori-agent

# Before hooks - run before the build
before:
  hooks:
    # Install dependencies
    - go mod tidy
    # Build internal plugins (required for complete distribution)
    - ./scripts/build-plugins.sh
    # Build external/shared plugins
    - ./scripts/build-external-plugins.sh

# Build configuration
builds:
  # Server binary (main application)
  - id: server
    main: ./cmd/server
    binary: ori-agent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/johnjallday/ori-agent/internal/version.Version={{.Version}}'
      - -X 'github.com/johnjallday/ori-agent/internal/version.GitCommit={{.ShortCommit}}'
      - -X 'github.com/johnjallday/ori-agent/internal/version.BuildDate={{.Date}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude invalid combinations
    ignore:
      - goos: windows
        goarch: arm64  # Windows ARM64 support is experimental

  # Menu bar app (macOS only)
  - id: menubar
    main: ./cmd/menubar
    binary: ori-menubar
    env:
      - CGO_ENABLED=1  # Required for system tray integration
    ldflags:
      - -s -w
      - -X 'github.com/johnjallday/ori-agent/internal/version.Version={{.Version}}'
      - -X 'github.com/johnjallday/ori-agent/internal/version.GitCommit={{.ShortCommit}}'
      - -X 'github.com/johnjallday/ori-agent/internal/version.BuildDate={{.Date}}'
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

# Archives configuration
# Note: Archives are created for all platforms, but the main distribution
# happens through platform-specific installers (DMG, MSI, deb/rpm)
# Only archive the server binary (menubar is bundled separately in DMG)
archives:
  - id: default
    ids:
      - server
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      # Note: Plugin binaries excluded to reduce archive size
      # Users can build plugins with: ./scripts/build-plugins.sh
      # Or use platform-specific installers (DMG, deb, rpm) which include plugins

# macOS DMG installers - created via custom publisher
publishers:
  - name: macos-dmg-amd64
    ids:
      - default
    cmd: ./build/macos/create-dmg.sh {{ .Version }} {{ .Os }} {{ .Arch }} dist
    env:
      - PATH={{ .Env.PATH }}
      - TARGET_ARCH=amd64
    extra_files:
      - glob: ./dist/ori-menubar_darwin_amd64/*
      - glob: ./dist/ori-agent_darwin_amd64/*

  - name: macos-dmg-arm64
    ids:
      - default
    cmd: ./build/macos/create-dmg.sh {{ .Version }} {{ .Os }} {{ .Arch }} dist
    env:
      - PATH={{ .Env.PATH }}
      - TARGET_ARCH=arm64
    extra_files:
      - glob: ./dist/ori-menubar_darwin_arm64/*
      - glob: ./dist/ori-agent_darwin_arm64/*

# Windows MSI installers - created via custom script on Windows runner
# Note: MSI creation is handled in GitHub Actions on windows-latest runner
# See .github/workflows/release.yml for Windows-specific build steps

# Linux packages - .deb and .rpm via nfpm
nfpms:
  - id: linux-packages
    package_name: ori-agent
    vendor: Ori
    homepage: https://github.com/johnjallday/ori-agent
    maintainer: Ori Team <noreply@github.com>
    description: |
      Ori Agent - Modular AI Agent Framework

      A plugin-driven framework for building tool-calling AI agents with support
      for multiple LLM providers (OpenAI, Claude, Ollama) and a flexible plugin system.
    license: MIT

    # Package formats
    formats:
      - deb     # Debian/Ubuntu
      - rpm     # Red Hat/Fedora/CentOS

    # Binary installation directory
    bindir: /usr/bin

    # File mappings
    contents:
      # Systemd service file
      - src: build/linux/ori-agent.service
        dst: /lib/systemd/system/ori-agent.service
        file_info:
          mode: 0644

      # Desktop application entry
      - src: build/linux/ori-agent.desktop
        dst: /usr/share/applications/ori-agent.desktop
        file_info:
          mode: 0644

      # Documentation
      - src: README.md
        dst: /usr/share/doc/ori-agent/README.md
        file_info:
          mode: 0644

      - src: LICENSE
        dst: /usr/share/doc/ori-agent/LICENSE
        file_info:
          mode: 0644

      # Create empty directories
      - dst: /var/lib/ori-agent
        type: dir
        file_info:
          mode: 0755

      - dst: /var/log/ori-agent
        type: dir
        file_info:
          mode: 0755

      - dst: /etc/ori-agent
        type: dir
        file_info:
          mode: 0755

    # Scripts
    scripts:
      postinstall: build/linux/postinstall.sh
      preremove: build/linux/preremove.sh
      postremove: build/linux/postremove.sh

    # Dependencies (optional - most systems have these)
    # recommends:
    #   - ca-certificates

    # RPM-specific configuration
    rpm:
      compression: lzma
      group: Development/Tools

    # Debian-specific configuration
    deb:
      compression: xz
      fields:
        Priority: optional

# Checksums
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Snapshots - for testing releases locally
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Dependency Updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 4
    - title: Other Changes
      order: 999

# GitHub Release configuration
release:
  github:
    owner: johnjallday
    name: ori-agent
  draft: false
  prerelease: auto
  mode: replace
  # Disable parallel uploads to prevent rate limiting and timeouts
  disable: false
  # Upload files sequentially with retries
  extra_files:
    - glob: ./dist/*.dmg
  header: |
    ## Ori Agent {{ .Tag }}

    Welcome to this new release of **Ori Agent**!

    ### Installation

    **Choose the installer for your platform:**

    - **macOS**:
      - Apple Silicon (M1/M2/M3): `OriAgent-{{ .Version }}-arm64.dmg`
      - Intel: `OriAgent-{{ .Version }}-amd64.dmg`

    - **Windows**:
      - `ori-agent-{{ .Version }}-amd64.msi` (recommended - full installer)
      - `ori-agent_{{ .Version }}_windows_amd64.exe` (standalone binary)

    - **Linux**:
      - **Debian/Ubuntu**: `ori-agent_{{ .Version }}_amd64.deb` or `ori-agent_{{ .Version }}_arm64.deb`
      - **Red Hat/Fedora/CentOS**: `ori-agent_{{ .Version }}_amd64.rpm` or `ori-agent_{{ .Version }}_arm64.rpm`

    For detailed installation instructions, see the [documentation](https://github.com/johnjallday/ori-agent#installation).
  footer: |
    ---

    **Full Changelog**: https://github.com/johnjallday/ori-agent/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Verification

    All binaries are checksummed. Verify downloads with:
    ```bash
    sha256sum -c checksums.txt
    ```
  name_template: "v{{.Version}}"

# Announce - future feature for announcing releases
# announce:
#   skip: true

# Metadata
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

# Dist directory
dist: dist

# Git configuration
git:
  ignore_tags:
    - nightly

# Sign artifacts - Phase 4 (code signing)
# signs:
#   - artifacts: checksum
