// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: pluginapi/proto/tool.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for RPCs that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{0}
}

// FunctionDefinition represents an OpenAI function definition
type FunctionDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON-encoded OpenAI parameters schema
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// CallRequest contains the arguments for calling a tool
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgsJson      string                 `protobuf:"bytes,1,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // JSON-encoded tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{2}
}

func (x *CallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// CallResponse contains the result of a tool call
type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON-encoded result on success
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{3}
}

func (x *CallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VersionResponse contains the plugin version
type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AgentContextRequest provides current agent information to the plugin
type AgentContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // Agent name (e.g., "default", "my-agent")
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`       // Path to agent's config.json
	SettingsPath  string                 `protobuf:"bytes,3,opt,name=settings_path,json=settingsPath,proto3" json:"settings_path,omitempty"` // Path to agent's agent_settings.json
	AgentDir      string                 `protobuf:"bytes,4,opt,name=agent_dir,json=agentDir,proto3" json:"agent_dir,omitempty"`             // Path to agent's directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentContextRequest) Reset() {
	*x = AgentContextRequest{}
	mi := &file_pluginapi_proto_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContextRequest) ProtoMessage() {}

func (x *AgentContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginapi_proto_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContextRequest.ProtoReflect.Descriptor instead.
func (*AgentContextRequest) Descriptor() ([]byte, []int) {
	return file_pluginapi_proto_tool_proto_rawDescGZIP(), []int{5}
}

func (x *AgentContextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentContextRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *AgentContextRequest) GetSettingsPath() string {
	if x != nil {
		return x.SettingsPath
	}
	return ""
}

func (x *AgentContextRequest) GetAgentDir() string {
	if x != nil {
		return x.AgentDir
	}
	return ""
}

var File_pluginapi_proto_tool_proto protoreflect.FileDescriptor

const file_pluginapi_proto_tool_proto_rawDesc = "" +
	"\n" +
	"\x1apluginapi/proto/tool.proto\x12\tpluginapi\"\a\n" +
	"\x05Empty\"s\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"*\n" +
	"\vCallRequest\x12\x1b\n" +
	"\targs_json\x18\x01 \x01(\tR\bargsJson\"E\n" +
	"\fCallResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x8c\x01\n" +
	"\x13AgentContextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12#\n" +
	"\rsettings_path\x18\x03 \x01(\tR\fsettingsPath\x12\x1b\n" +
	"\tagent_dir\x18\x04 \x01(\tR\bagentDir2\x89\x02\n" +
	"\vToolService\x12@\n" +
	"\rGetDefinition\x12\x10.pluginapi.Empty\x1a\x1d.pluginapi.FunctionDefinition\x127\n" +
	"\x04Call\x12\x16.pluginapi.CallRequest\x1a\x17.pluginapi.CallResponse\x12:\n" +
	"\n" +
	"GetVersion\x12\x10.pluginapi.Empty\x1a\x1a.pluginapi.VersionResponse\x12C\n" +
	"\x0fSetAgentContext\x12\x1e.pluginapi.AgentContextRequest\x1a\x10.pluginapi.EmptyB0Z.github.com/johnjallday/dolphin-agent/pluginapib\x06proto3"

var (
	file_pluginapi_proto_tool_proto_rawDescOnce sync.Once
	file_pluginapi_proto_tool_proto_rawDescData []byte
)

func file_pluginapi_proto_tool_proto_rawDescGZIP() []byte {
	file_pluginapi_proto_tool_proto_rawDescOnce.Do(func() {
		file_pluginapi_proto_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginapi_proto_tool_proto_rawDesc), len(file_pluginapi_proto_tool_proto_rawDesc)))
	})
	return file_pluginapi_proto_tool_proto_rawDescData
}

var file_pluginapi_proto_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pluginapi_proto_tool_proto_goTypes = []any{
	(*Empty)(nil),               // 0: pluginapi.Empty
	(*FunctionDefinition)(nil),  // 1: pluginapi.FunctionDefinition
	(*CallRequest)(nil),         // 2: pluginapi.CallRequest
	(*CallResponse)(nil),        // 3: pluginapi.CallResponse
	(*VersionResponse)(nil),     // 4: pluginapi.VersionResponse
	(*AgentContextRequest)(nil), // 5: pluginapi.AgentContextRequest
}
var file_pluginapi_proto_tool_proto_depIdxs = []int32{
	0, // 0: pluginapi.ToolService.GetDefinition:input_type -> pluginapi.Empty
	2, // 1: pluginapi.ToolService.Call:input_type -> pluginapi.CallRequest
	0, // 2: pluginapi.ToolService.GetVersion:input_type -> pluginapi.Empty
	5, // 3: pluginapi.ToolService.SetAgentContext:input_type -> pluginapi.AgentContextRequest
	1, // 4: pluginapi.ToolService.GetDefinition:output_type -> pluginapi.FunctionDefinition
	3, // 5: pluginapi.ToolService.Call:output_type -> pluginapi.CallResponse
	4, // 6: pluginapi.ToolService.GetVersion:output_type -> pluginapi.VersionResponse
	0, // 7: pluginapi.ToolService.SetAgentContext:output_type -> pluginapi.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pluginapi_proto_tool_proto_init() }
func file_pluginapi_proto_tool_proto_init() {
	if File_pluginapi_proto_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginapi_proto_tool_proto_rawDesc), len(file_pluginapi_proto_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginapi_proto_tool_proto_goTypes,
		DependencyIndexes: file_pluginapi_proto_tool_proto_depIdxs,
		MessageInfos:      file_pluginapi_proto_tool_proto_msgTypes,
	}.Build()
	File_pluginapi_proto_tool_proto = out.File
	file_pluginapi_proto_tool_proto_goTypes = nil
	file_pluginapi_proto_tool_proto_depIdxs = nil
}
