// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDirectory(arg1:string,arg2:string,arg3:string):Promise<main.DirectoryResult>;

export function CheckServerConnection():Promise<boolean>;

export function GetPreSelectedWorkspace():Promise<string>;

export function GetWorkspaces():Promise<Array<main.Workspace>>;

export function HideWindow():Promise<void>;

export function OpenFolderDialog():Promise<string>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;

export function ValidatePath(arg1:string):Promise<main.DirectoryResult>;
