// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDirectory'](arg1, arg2, arg3);
}

export function CheckServerConnection() {
  return window['go']['main']['App']['CheckServerConnection']();
}

export function GetPreSelectedWorkspace() {
  return window['go']['main']['App']['GetPreSelectedWorkspace']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
