// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/tool.proto

package pluginapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message for RPCs that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{0}
}

// FunctionDefinition represents an OpenAI function definition
type FunctionDefinition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"` // JSON-encoded OpenAI parameters schema
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FunctionDefinition) Reset() {
	*x = FunctionDefinition{}
	mi := &file_proto_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDefinition) ProtoMessage() {}

func (x *FunctionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDefinition.ProtoReflect.Descriptor instead.
func (*FunctionDefinition) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionDefinition) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

// CallRequest contains the arguments for calling a tool
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArgsJson      string                 `protobuf:"bytes,1,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"` // JSON-encoded tool arguments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_proto_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{2}
}

func (x *CallRequest) GetArgsJson() string {
	if x != nil {
		return x.ArgsJson
	}
	return ""
}

// CallResponse contains the result of a tool call
type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"` // JSON-encoded result on success
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_proto_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{3}
}

func (x *CallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *CallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// VersionResponse contains the plugin version
type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{4}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AgentContextRequest provides current agent information to the plugin
type AgentContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                     // Agent name (e.g., "default", "my-agent")
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`       // Path to agent's config.json
	SettingsPath  string                 `protobuf:"bytes,3,opt,name=settings_path,json=settingsPath,proto3" json:"settings_path,omitempty"` // Path to agent's agent_settings.json
	AgentDir      string                 `protobuf:"bytes,4,opt,name=agent_dir,json=agentDir,proto3" json:"agent_dir,omitempty"`             // Path to agent's directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentContextRequest) Reset() {
	*x = AgentContextRequest{}
	mi := &file_proto_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentContextRequest) ProtoMessage() {}

func (x *AgentContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentContextRequest.ProtoReflect.Descriptor instead.
func (*AgentContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{5}
}

func (x *AgentContextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentContextRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *AgentContextRequest) GetSettingsPath() string {
	if x != nil {
		return x.SettingsPath
	}
	return ""
}

func (x *AgentContextRequest) GetAgentDir() string {
	if x != nil {
		return x.AgentDir
	}
	return ""
}

// SettingsResponse contains plugin settings as JSON
type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingsJson  string                 `protobuf:"bytes,1,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"` // JSON-encoded settings
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                   // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_proto_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{6}
}

func (x *SettingsResponse) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

func (x *SettingsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ConfigVariable describes a single configuration variable
type ConfigVariable struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Key              string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "string", "int", "filepath", "dirpath", "password", etc.
	Required         bool                   `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValueJson string                 `protobuf:"bytes,6,opt,name=default_value_json,json=defaultValueJson,proto3" json:"default_value_json,omitempty"` // JSON-encoded default value (optional)
	Validation       string                 `protobuf:"bytes,7,opt,name=validation,proto3" json:"validation,omitempty"`                                       // Validation rules (optional)
	Options          []string               `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`                                             // List of valid options (optional)
	Placeholder      string                 `protobuf:"bytes,9,opt,name=placeholder,proto3" json:"placeholder,omitempty"`                                     // Placeholder text (optional)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigVariable) Reset() {
	*x = ConfigVariable{}
	mi := &file_proto_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVariable) ProtoMessage() {}

func (x *ConfigVariable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVariable.ProtoReflect.Descriptor instead.
func (*ConfigVariable) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigVariable) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigVariable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigVariable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigVariable) GetDefaultValueJson() string {
	if x != nil {
		return x.DefaultValueJson
	}
	return ""
}

func (x *ConfigVariable) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

func (x *ConfigVariable) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ConfigVariable) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// ConfigVariablesResponse contains the list of required config variables
type ConfigVariablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVars    []*ConfigVariable      `protobuf:"bytes,1,rep,name=config_vars,json=configVars,proto3" json:"config_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVariablesResponse) Reset() {
	*x = ConfigVariablesResponse{}
	mi := &file_proto_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVariablesResponse) ProtoMessage() {}

func (x *ConfigVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVariablesResponse.ProtoReflect.Descriptor instead.
func (*ConfigVariablesResponse) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigVariablesResponse) GetConfigVars() []*ConfigVariable {
	if x != nil {
		return x.ConfigVars
	}
	return nil
}

// ValidateConfigRequest contains configuration to validate
type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON-encoded configuration map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_proto_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// InitializeConfigRequest contains configuration for initialization
type InitializeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON-encoded configuration map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeConfigRequest) Reset() {
	*x = InitializeConfigRequest{}
	mi := &file_proto_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeConfigRequest) ProtoMessage() {}

func (x *InitializeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeConfigRequest.ProtoReflect.Descriptor instead.
func (*InitializeConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{10}
}

func (x *InitializeConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// ConfigResponse contains the result of config operations
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message on failure (empty on success)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_proto_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_tool_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_tool_proto protoreflect.FileDescriptor

const file_proto_tool_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tool.proto\x12\tpluginapi\"\a\n" +
	"\x05Empty\"s\n" +
	"\x12FunctionDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"*\n" +
	"\vCallRequest\x12\x1b\n" +
	"\targs_json\x18\x01 \x01(\tR\bargsJson\"E\n" +
	"\fCallResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x8c\x01\n" +
	"\x13AgentContextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12#\n" +
	"\rsettings_path\x18\x03 \x01(\tR\fsettingsPath\x12\x1b\n" +
	"\tagent_dir\x18\x04 \x01(\tR\bagentDir\"M\n" +
	"\x10SettingsResponse\x12#\n" +
	"\rsettings_json\x18\x01 \x01(\tR\fsettingsJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x02\n" +
	"\x0eConfigVariable\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12,\n" +
	"\x12default_value_json\x18\x06 \x01(\tR\x10defaultValueJson\x12\x1e\n" +
	"\n" +
	"validation\x18\a \x01(\tR\n" +
	"validation\x12\x18\n" +
	"\aoptions\x18\b \x03(\tR\aoptions\x12 \n" +
	"\vplaceholder\x18\t \x01(\tR\vplaceholder\"U\n" +
	"\x17ConfigVariablesResponse\x12:\n" +
	"\vconfig_vars\x18\x01 \x03(\v2\x19.pluginapi.ConfigVariableR\n" +
	"configVars\"8\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\":\n" +
	"\x17InitializeConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"@\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xbf\x04\n" +
	"\vToolService\x12@\n" +
	"\rGetDefinition\x12\x10.pluginapi.Empty\x1a\x1d.pluginapi.FunctionDefinition\x127\n" +
	"\x04Call\x12\x16.pluginapi.CallRequest\x1a\x17.pluginapi.CallResponse\x12:\n" +
	"\n" +
	"GetVersion\x12\x10.pluginapi.Empty\x1a\x1a.pluginapi.VersionResponse\x12C\n" +
	"\x0fSetAgentContext\x12\x1e.pluginapi.AgentContextRequest\x1a\x10.pluginapi.Empty\x12C\n" +
	"\x12GetDefaultSettings\x12\x10.pluginapi.Empty\x1a\x1b.pluginapi.SettingsResponse\x12I\n" +
	"\x11GetRequiredConfig\x12\x10.pluginapi.Empty\x1a\".pluginapi.ConfigVariablesResponse\x12M\n" +
	"\x0eValidateConfig\x12 .pluginapi.ValidateConfigRequest\x1a\x19.pluginapi.ConfigResponse\x12U\n" +
	"\x14InitializeWithConfig\x12\".pluginapi.InitializeConfigRequest\x1a\x19.pluginapi.ConfigResponseB,Z*github.com/johnjallday/ori-agent/pluginapib\x06proto3"

var (
	file_proto_tool_proto_rawDescOnce sync.Once
	file_proto_tool_proto_rawDescData []byte
)

func file_proto_tool_proto_rawDescGZIP() []byte {
	file_proto_tool_proto_rawDescOnce.Do(func() {
		file_proto_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tool_proto_rawDesc), len(file_proto_tool_proto_rawDesc)))
	})
	return file_proto_tool_proto_rawDescData
}

var file_proto_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_tool_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: pluginapi.Empty
	(*FunctionDefinition)(nil),      // 1: pluginapi.FunctionDefinition
	(*CallRequest)(nil),             // 2: pluginapi.CallRequest
	(*CallResponse)(nil),            // 3: pluginapi.CallResponse
	(*VersionResponse)(nil),         // 4: pluginapi.VersionResponse
	(*AgentContextRequest)(nil),     // 5: pluginapi.AgentContextRequest
	(*SettingsResponse)(nil),        // 6: pluginapi.SettingsResponse
	(*ConfigVariable)(nil),          // 7: pluginapi.ConfigVariable
	(*ConfigVariablesResponse)(nil), // 8: pluginapi.ConfigVariablesResponse
	(*ValidateConfigRequest)(nil),   // 9: pluginapi.ValidateConfigRequest
	(*InitializeConfigRequest)(nil), // 10: pluginapi.InitializeConfigRequest
	(*ConfigResponse)(nil),          // 11: pluginapi.ConfigResponse
}
var file_proto_tool_proto_depIdxs = []int32{
	7,  // 0: pluginapi.ConfigVariablesResponse.config_vars:type_name -> pluginapi.ConfigVariable
	0,  // 1: pluginapi.ToolService.GetDefinition:input_type -> pluginapi.Empty
	2,  // 2: pluginapi.ToolService.Call:input_type -> pluginapi.CallRequest
	0,  // 3: pluginapi.ToolService.GetVersion:input_type -> pluginapi.Empty
	5,  // 4: pluginapi.ToolService.SetAgentContext:input_type -> pluginapi.AgentContextRequest
	0,  // 5: pluginapi.ToolService.GetDefaultSettings:input_type -> pluginapi.Empty
	0,  // 6: pluginapi.ToolService.GetRequiredConfig:input_type -> pluginapi.Empty
	9,  // 7: pluginapi.ToolService.ValidateConfig:input_type -> pluginapi.ValidateConfigRequest
	10, // 8: pluginapi.ToolService.InitializeWithConfig:input_type -> pluginapi.InitializeConfigRequest
	1,  // 9: pluginapi.ToolService.GetDefinition:output_type -> pluginapi.FunctionDefinition
	3,  // 10: pluginapi.ToolService.Call:output_type -> pluginapi.CallResponse
	4,  // 11: pluginapi.ToolService.GetVersion:output_type -> pluginapi.VersionResponse
	0,  // 12: pluginapi.ToolService.SetAgentContext:output_type -> pluginapi.Empty
	6,  // 13: pluginapi.ToolService.GetDefaultSettings:output_type -> pluginapi.SettingsResponse
	8,  // 14: pluginapi.ToolService.GetRequiredConfig:output_type -> pluginapi.ConfigVariablesResponse
	11, // 15: pluginapi.ToolService.ValidateConfig:output_type -> pluginapi.ConfigResponse
	11, // 16: pluginapi.ToolService.InitializeWithConfig:output_type -> pluginapi.ConfigResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tool_proto_init() }
func file_proto_tool_proto_init() {
	if File_proto_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tool_proto_rawDesc), len(file_proto_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tool_proto_goTypes,
		DependencyIndexes: file_proto_tool_proto_depIdxs,
		MessageInfos:      file_proto_tool_proto_msgTypes,
	}.Build()
	File_proto_tool_proto = out.File
	file_proto_tool_proto_goTypes = nil
	file_proto_tool_proto_depIdxs = nil
}
