package reaper

import (
	"errors"
	"strconv"
	"strings"
)

// Track edits are the mutations that have no REAPER command ID, so each one is
// generated Lua run through the installed runner.
//
// REAPER's Web Remote identifies tracks only by position — there is no GUID at
// read time — so every edit is a compare-and-swap: the generated Lua re-reads
// the name at the index and applies the change only if it still matches the
// name Ori believed was there. This is the correctness centre of the feature.
// The Lua also captures the prior value into a receipt file so the server can
// build a specific inverse for Undo.
const (
	TrackEditRename = "rename"

	// receiptFileName sits beside last_status.txt under the canonical runner
	// root and is cleared before every run.
	receiptFileName = "last_receipt.txt"

	// maxTrackNameBytes bounds a name well below anything REAPER accepts, so
	// generated Lua stays small and a hostile name cannot balloon the script.
	maxTrackNameBytes = 512
)

var (
	ErrInvalidTrackEdit = errors.New("invalid REAPER track edit")
	ErrInvalidReceipt   = errors.New("invalid REAPER edit receipt")
)

// TrackEdit is one guarded single-track mutation. Index is 1-based to match
// the Web Remote TRACK line the console rendered from; ExpectedName is the
// guard, and the empty string is a legitimate value because REAPER reports an
// unnamed track's name as empty on both the Web Remote and P_NAME paths.
type TrackEdit struct {
	Kind         string
	Index        int
	ExpectedName string
	NewName      string
}

// RenameEdit builds a guarded rename.
func RenameEdit(index int, expectedName, newName string) TrackEdit {
	return TrackEdit{Kind: TrackEditRename, Index: index, ExpectedName: expectedName, NewName: newName}
}

// Inverse returns the edit that reverses this one, guarded on the value Ori
// wrote. Applying it is only correct when the forward edit actually applied,
// so callers must build it from the receipt rather than from hope.
func (e TrackEdit) Inverse(priorName string) TrackEdit {
	return TrackEdit{
		Kind:         TrackEditRename,
		Index:        e.Index,
		ExpectedName: e.NewName,
		NewName:      priorName,
	}
}

// Validate rejects an edit before any Lua is generated.
func (e TrackEdit) Validate() error {
	if e.Kind != TrackEditRename {
		return ErrInvalidTrackEdit
	}
	if e.Index < 1 {
		return ErrInvalidTrackEdit
	}
	if len(e.ExpectedName) > maxTrackNameBytes || len(e.NewName) > maxTrackNameBytes {
		return ErrInvalidTrackEdit
	}
	if strings.TrimSpace(e.NewName) == "" {
		return ErrInvalidTrackEdit
	}
	return nil
}

// Lua generates the guarded script for this edit. receiptPath is a trusted
// absolute path under the canonical runner root, supplied by the Runner; it is
// never derived from a browser request and never travels back to one.
func (e TrackEdit) Lua(receiptPath string) (string, error) {
	if err := e.Validate(); err != nil {
		return "", err
	}
	if !strings.HasPrefix(receiptPath, "/") || strings.Contains(receiptPath, "\n") {
		return "", ErrInvalidTrackEdit
	}

	var script strings.Builder
	script.WriteString("-- Generated by Ori: guarded single-track edit.\n")
	script.WriteString("local receipt_path = " + luaString(receiptPath) + "\n")
	script.WriteString("local expected = " + luaString(e.ExpectedName) + "\n")
	script.WriteString("local new_value = " + luaString(e.NewName) + "\n")
	script.WriteString("local index = " + strconv.Itoa(e.Index) + "\n\n")
	script.WriteString(`local function write_receipt(body)
  local file = io.open(receipt_path, "wb")
  if file then
    file:write(body)
    file:close()
  end
end

-- Compare and swap: REAPER identifies tracks only by position, so refuse
-- rather than guess if the track at this index is no longer the one Ori read.
local tr = reaper.GetTrack(0, index - 1)
if not tr then
  write_receipt("guard_failed\n")
  return
end

local ok, current = reaper.GetSetMediaTrackInfo_String(tr, "P_NAME", "", false)
if not ok or current ~= expected then
  write_receipt("guard_failed\n")
  return
end

reaper.Undo_BeginBlock()
reaper.GetSetMediaTrackInfo_String(tr, "P_NAME", new_value, true)
reaper.Undo_EndBlock("Ori: rename track", -1)
reaper.TrackList_AdjustWindows(false)
reaper.UpdateArrange()

write_receipt("applied\n" .. current)
`)
	return script.String(), nil
}

// EditReceipt is what the generated Lua reported back. Applied is the
// authority on whether the project changed: the runner reports ok whenever the
// script itself ran cleanly, including when the guard deliberately refused.
type EditReceipt struct {
	Applied bool
	Prior   string
}

// ParseEditReceipt reads the receipt contract: the first line is the outcome,
// and everything after the first newline is the prior value verbatim so names
// containing spaces round-trip intact.
func ParseEditReceipt(data []byte) (EditReceipt, error) {
	text := string(data)
	outcome := text
	prior := ""
	if newline := strings.IndexByte(text, '\n'); newline >= 0 {
		outcome = text[:newline]
		prior = text[newline+1:]
	}
	switch strings.TrimSpace(outcome) {
	case "applied":
		return EditReceipt{Applied: true, Prior: prior}, nil
	case "guard_failed":
		return EditReceipt{Applied: false}, nil
	default:
		return EditReceipt{}, ErrInvalidReceipt
	}
}

// luaString encodes a Go string as a Lua literal using decimal byte escapes.
// Quotes, newlines, backslashes, and long-bracket sequences in a user-supplied
// track name therefore cannot terminate the literal or inject code.
func luaString(value string) string {
	var quoted strings.Builder
	quoted.Grow(len(value)*4 + 2)
	quoted.WriteByte('"')
	for i := 0; i < len(value); i++ {
		quoted.WriteByte('\\')
		quoted.WriteString(strconv.Itoa(int(value[i])))
	}
	quoted.WriteByte('"')
	return quoted.String()
}
