// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*storeTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool    = (*storeTool)(nil)
	_ pluginapi.MetadataProvider = (*storeTool)(nil)
)

// StoreParams represents the parameters for this plugin
type StoreParams struct {
	StoreNodeId string                 `json:"store_node_id"` // The canvas node ID of the store node (e.g., 'store-node-1')
	FilePath    string                 `json:"file_path"`     // Relative path within the store node's base directory (e.g., 'reports/daily.json'). Path is validated to prevent directory traversal.
	Data        string                 `json:"data"`          // The data to write. Format depends on the store node's configured format (json, text, markdown, or base64-encoded binary).
	Metadata    map[string]interface{} `json:"metadata"`      // Optional metadata about the write operation (for logging/tracking)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *storeTool) Call(ctx context.Context, args string) (string, error) {
	var params StoreParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.StoreNodeId == "" {
		return "", fmt.Errorf("required field 'store_node_id' is missing")
	}
	if params.FilePath == "" {
		return "", fmt.Errorf("required field 'file_path' is missing")
	}
	if params.Data == "" {
		return "", fmt.Errorf("required field 'data' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
