// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*StoreTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool       = (*StoreTool)(nil)
	_ pluginapi.MetadataProvider    = (*StoreTool)(nil)
	_ pluginapi.PluginCompatibility = (*StoreTool)(nil)
)

//go:embed plugin.yaml
var configYAML string

// Params represents the parameters for this plugin
type Params struct {
	StoreNodeId string                 `json:"store_node_id"` // The canvas node ID of the Store node (e.g., 'store-node-1')
	FilePath    string                 `json:"file_path"`     // Relative path within the Store node's base directory (e.g., 'daily-2025-01-15.json', '2025/jan/report.txt'). Must be relative - no absolute paths or '../' allowed.
	Data        string                 `json:"data"`          // The data to write. Format depends on the Store node's configuration (JSON string, plain text, markdown, or base64-encoded binary)
	Metadata    map[string]interface{} `json:"metadata"`      // Optional metadata about the write operation (e.g., timestamp, source_task_id)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *StoreTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params Params

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method
	return t.Execute(ctx, &params)
}
