package projecttemplates_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/johnjallday/ori-agent/internal/projecttemplates"
	"github.com/johnjallday/ori-agent/internal/templateonboarding"
)

// smokeOnboardManifest is the non-REAPER onboarding fixture: two intake fields
// and a dependency-free `completion.type: "none"` action that instantiates the
// folder skeleton. It mirrors the template used in manual smoke verification of
// the non-REAPER completion path so the same template.json is exercised in CI.
const smokeOnboardManifest = `{
  "name": "Smoke Onboard",
  "description": "Non-REAPER onboarding fixture: collects two fields then instantiates a folder skeleton with no skill/MCP dependencies.",
  "tags": ["smoke", "onboarding"],
  "onboarding": {
    "version": "1",
    "fields": [
      {
        "id": "project_title",
        "label": "Project title",
        "type": "string",
        "required": true,
        "prompt": "Human-readable title used in the generated docs filename.",
        "validation": {"min": 1, "max": 80}
      },
      {
        "id": "track_count",
        "label": "Track count",
        "type": "number",
        "default": 8,
        "required": true,
        "prompt": "How many tracks to plan for.",
        "validation": {"min": 1, "max": 64}
      }
    ],
    "completion": {
      "type": "none",
      "instructions": "Skeleton-only completion; no agent action required.",
      "instantiate_skeleton": true
    }
  }
}`

// writeSmokeOnboardTemplate materializes the non-REAPER onboarding fixture as a
// library template folder under dir and returns the template's folder path. The
// skeleton carries {{name}} and {{fields.<id>}} tokens in file/folder names so
// instantiation substitution is exercised; file contents are intentionally left
// untouched (the engine only substitutes names).
func writeSmokeOnboardTemplate(t *testing.T, dir string) string {
	t.Helper()
	root := filepath.Join(dir, "smoke-onboard")
	if err := os.MkdirAll(filepath.Join(root, "docs"), 0o750); err != nil {
		t.Fatalf("mkdir template: %v", err)
	}
	files := map[string]string{
		"template.json":     smokeOnboardManifest,
		"README.md":         "# Project skeleton\n\nGenerated by the smoke-onboard template.\n",
		"{{name}}-info.txt": "project: {{name}}\ndate: {{date}}\n",
		"docs/{{fields.project_title}}-overview.md": "Overview for {{fields.project_title}} with {{fields.track_count}} tracks.\n",
	}
	for rel, content := range files {
		if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(rel)), []byte(content), 0o640); err != nil {
			t.Fatalf("write %s: %v", rel, err)
		}
	}
	return root
}

// TestSmokeOnboardTemplateOnboardingSpecValid checks the fixture's onboarding
// block parses and validates with the expected dependency-free, skeleton-only
// completion. This is the static half of the non-REAPER smoke coverage.
func TestSmokeOnboardTemplateOnboardingSpecValid(t *testing.T) {
	libDir := filepath.Join(t.TempDir(), "templates")
	writeSmokeOnboardTemplate(t, libDir)

	tpl, err := projecttemplates.FindLibraryTemplate(libDir, "smoke-onboard")
	if err != nil {
		t.Fatalf("FindLibraryTemplate: %v", err)
	}
	if !tpl.HasOnboarding() {
		t.Fatalf("expected smoke-onboard template to carry an onboarding block")
	}
	spec, err := templateonboarding.ParseSpec(tpl.Onboarding)
	if err != nil {
		t.Fatalf("ParseSpec: %v", err)
	}
	if res := templateonboarding.Validate(spec); !res.OK() {
		t.Fatalf("Validate: %v", res.Err())
	}
	if len(spec.Fields) != 2 || spec.Fields[0].ID != "project_title" || spec.Fields[1].ID != "track_count" {
		t.Fatalf("unexpected onboarding fields: %+v", spec.Fields)
	}
	if spec.Completion.Type != templateonboarding.ActionNone || !spec.Completion.InstantiateSkeleton {
		t.Fatalf("completion = %+v, want none with skeleton instantiation", spec.Completion)
	}
	if len(spec.Dependencies) != 0 {
		t.Fatalf("expected no dependencies, got %+v", spec.Dependencies)
	}
}

// TestSmokeOnboardTemplateInstantiatesSkeleton drives the real instantiation
// path the non-REAPER completion runs: collected field values are slugified into
// {{name}} and {{fields.<id>}} filename tokens, template.json is excluded, and
// file contents are byte-copied verbatim.
func TestSmokeOnboardTemplateInstantiatesSkeleton(t *testing.T) {
	libDir := filepath.Join(t.TempDir(), "templates")
	templatePath := writeSmokeOnboardTemplate(t, libDir)

	workspaceFolder := t.TempDir()
	fieldValues := map[string]any{
		"project_title": "My Smoke Song",
		"track_count":   12,
	}

	relPath, err := projecttemplates.InstantiateWithFields(templatePath, workspaceFolder, "Smoke Song", fieldValues)
	if err != nil {
		t.Fatalf("InstantiateWithFields: %v", err)
	}
	if relPath != "smoke-song" {
		t.Fatalf("project rel path = %q, want %q", relPath, "smoke-song")
	}

	projectDir := filepath.Join(workspaceFolder, relPath)
	// {{name}} -> project slug; {{fields.project_title}} -> slugified value.
	wantFiles := []string{
		"README.md",
		"smoke-song-info.txt",
		filepath.Join("docs", "my-smoke-song-overview.md"),
	}
	for _, rel := range wantFiles {
		if _, err := os.Stat(filepath.Join(projectDir, rel)); err != nil {
			t.Fatalf("expected instantiated file %s: %v", rel, err)
		}
	}

	if _, err := os.Stat(filepath.Join(projectDir, "template.json")); !os.IsNotExist(err) {
		t.Fatalf("template.json should be excluded from the instantiated project (stat err = %v)", err)
	}

	// Contents are byte-copied: name tokens are substituted, content tokens are not.
	content, err := os.ReadFile(filepath.Join(projectDir, "docs", "my-smoke-song-overview.md"))
	if err != nil {
		t.Fatalf("read overview: %v", err)
	}
	if want := "Overview for {{fields.project_title}} with {{fields.track_count}} tracks.\n"; string(content) != want {
		t.Fatalf("overview content = %q, want %q (file contents must not be token-substituted)", string(content), want)
	}
}
