package projecttemplates

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/johnjallday/ori-agent/internal/specialist"
	"github.com/johnjallday/ori-agent/internal/workspace"
)

const (
	maxUserSetupQuestBytes = specialist.MaxSetupJourneyBytes + 256
	userQuestSource        = "user_template"
)

var (
	ErrInvalidUserSetupQuest = errors.New("invalid user setup quest")
	ErrUserSetupQuestStale   = errors.New("user setup quest changed in another window")
	ErrUserSetupQuestLocked  = errors.New("user setup quest is locked by setup progress")

	userSetupQuestAttachmentPattern = regexp.MustCompile(`^uqatt_[a-f0-9]{24}$`)
	userSetupQuestIDPattern         = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]{0,63}$`)
	userSetupQuestURLPattern        = regexp.MustCompile(`(?i)([a-z][a-z0-9+.-]{1,15}://|(https?|file|javascript|data|ftp|mailto):|www\.|(^|[[:space:]])/api/)`)
)

// UserSetupQuest is one portable inert attachment on a user-owned template.
// AttachmentID is generated by the host. Declaration uses the same strict
// bounded vocabulary as plugin quests; OwnerPluginID always remains empty.
type UserSetupQuest struct {
	AttachmentID string
	Declaration  *specialist.SetupJourney
}

// UserSetupQuestDraft is the only authorable quest shape. Stable IDs,
// schema/version, source/owner, target references and step kinds are generated
// or verified by the host rather than accepted from this value.
type UserSetupQuestDraft struct {
	Title           string                          `json:"title"`
	Description     string                          `json:"description"`
	IntegrationKey  string                          `json:"integration_key"`
	Steps           []UserSetupQuestStepDraft       `json:"steps"`
	WorkspaceLaunch *specialist.WorkspaceLaunchCopy `json:"workspace_launch"`
}

type UserSetupQuestStepDraft struct {
	Kind        specialist.SetupStepKind `json:"kind"`
	Title       string                   `json:"title"`
	Description string                   `json:"description"`
}

type userSetupQuestDocument struct {
	Source                     string                          `json:"source"`
	AttachmentID               string                          `json:"attachment_id"`
	SchemaVersion              int                             `json:"schema_version"`
	Version                    int                             `json:"version"`
	ID                         string                          `json:"id"`
	Title                      string                          `json:"title"`
	Description                string                          `json:"description"`
	IntegrationKey             string                          `json:"integration_key"`
	ExpectedBlueprintID        string                          `json:"expected_blueprint_id"`
	ExpectedAssistantProgramID string                          `json:"expected_assistant_program_id"`
	Steps                      []specialist.SetupJourneyStep   `json:"steps"`
	WorkspaceLaunch            *specialist.WorkspaceLaunchCopy `json:"workspace_launch,omitempty"`
}

// UserSetupQuestEligibility is bounded, actionable authoring metadata. Codes
// are stable for clients; messages contain no paths or downstream errors.
type UserSetupQuestEligibility struct {
	Eligible bool                                  `json:"eligible"`
	Missing  []UserSetupQuestEligibilityDiagnostic `json:"missing,omitempty"`
}

type UserSetupQuestEligibilityDiagnostic struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (q UserSetupQuest) MarshalJSON() ([]byte, error) {
	if q.Declaration == nil {
		return []byte("null"), nil
	}
	d := q.Declaration
	return json.Marshal(userSetupQuestDocument{
		Source: userQuestSource, AttachmentID: q.AttachmentID, SchemaVersion: d.SchemaVersion, Version: d.Version,
		ID: d.ID, Title: d.Title, Description: d.Description, IntegrationKey: d.IntegrationKey,
		ExpectedBlueprintID: d.ExpectedBlueprintID, ExpectedAssistantProgramID: d.ExpectedAssistantProgramID,
		Steps: append([]specialist.SetupJourneyStep(nil), d.Steps...), WorkspaceLaunch: cloneUserQuestLaunch(d.WorkspaceLaunch),
	})
}

func (q *UserSetupQuest) UnmarshalJSON(data []byte) error {
	parsed, err := parseUserSetupQuest(data)
	if err != nil {
		return err
	}
	if parsed == nil {
		*q = UserSetupQuest{}
		return nil
	}
	*q = *parsed
	return nil
}

func (q *UserSetupQuest) Clone() *UserSetupQuest {
	if q == nil || q.Declaration == nil {
		return nil
	}
	encoded, err := json.Marshal(q)
	if err != nil {
		return nil
	}
	clone, err := parseUserSetupQuest(encoded)
	if err != nil {
		return nil
	}
	return clone
}

// ParseUserSetupQuest strictly parses a portable attachment without applying a
// template binding. Import and fixture boundaries use it before assigning a
// fresh local identity; normal template loading additionally validates target
// references against the effective template.
func ParseUserSetupQuest(data []byte) (*UserSetupQuest, error) {
	return parseUserSetupQuest(data)
}

func parseUserSetupQuest(data []byte) (*UserSetupQuest, error) {
	if len(bytes.TrimSpace(data)) == 0 || bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		return nil, nil
	}
	if len(data) > maxUserSetupQuestBytes {
		return nil, fmt.Errorf("%w: declaration exceeds %d bytes", ErrInvalidUserSetupQuest, maxUserSetupQuestBytes)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var document userSetupQuestDocument
	if err := decoder.Decode(&document); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidUserSetupQuest, err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("%w: trailing data", ErrInvalidUserSetupQuest)
	}
	document.Source = strings.ToLower(strings.TrimSpace(document.Source))
	document.AttachmentID = strings.ToLower(strings.TrimSpace(document.AttachmentID))
	if document.Source != userQuestSource {
		return nil, fmt.Errorf("%w: source must be user_template", ErrInvalidUserSetupQuest)
	}
	if !userSetupQuestAttachmentPattern.MatchString(document.AttachmentID) {
		return nil, fmt.Errorf("%w: attachment_id is not a host-generated identity", ErrInvalidUserSetupQuest)
	}
	declaration := specialist.SetupJourney{
		SchemaVersion: document.SchemaVersion, Version: document.Version, ID: document.ID,
		Title: document.Title, Description: document.Description, IntegrationKey: document.IntegrationKey,
		ExpectedBlueprintID:        document.ExpectedBlueprintID,
		ExpectedAssistantProgramID: document.ExpectedAssistantProgramID,
		Steps:                      append([]specialist.SetupJourneyStep(nil), document.Steps...),
		WorkspaceLaunch:            cloneUserQuestLaunch(document.WorkspaceLaunch),
	}
	normalized, err := specialist.NormalizeSetupJourney(declaration)
	if err != nil || normalized.WorkspaceLaunch == nil || normalized.OwnerPluginID != "" || userSetupQuestContainsURL(normalized) {
		if err == nil {
			err = errors.New("workspace_launch is required and display copy cannot contain URLs")
		}
		return nil, fmt.Errorf("%w: %v", ErrInvalidUserSetupQuest, err)
	}
	return &UserSetupQuest{AttachmentID: document.AttachmentID, Declaration: normalized}, nil
}

func userSetupQuestContainsURL(declaration *specialist.SetupJourney) bool {
	if declaration == nil {
		return false
	}
	values := []string{declaration.Title, declaration.Description}
	for _, step := range declaration.Steps {
		values = append(values, step.Title, step.Description)
	}
	if launch := declaration.WorkspaceLaunch; launch != nil {
		values = append(values, launch.GroupTitle, launch.GroupName, launch.RuntimeTitle, launch.RuntimeInstructions)
	}
	for _, value := range values {
		if userSetupQuestURLPattern.MatchString(value) {
			return true
		}
	}
	return false
}

func normalizeUserSetupQuest(raw json.RawMessage, template Template) (*UserSetupQuest, error) {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		return nil, nil
	}
	quest, err := parseUserSetupQuest(trimmed)
	if err != nil {
		return nil, err
	}
	if template.Builtin || template.PluginOwner != nil || strings.TrimSpace(template.SetupQuestID) != "" {
		return nil, fmt.Errorf("%w: user_setup_quest belongs only to a user-owned template", ErrInvalidUserSetupQuest)
	}
	if quest.Declaration.ExpectedBlueprintID != template.ID {
		return nil, fmt.Errorf("%w: expected_blueprint_id must match this template", ErrInvalidUserSetupQuest)
	}
	if template.AssistantProgram == nil || quest.Declaration.ExpectedAssistantProgramID != template.AssistantProgram.ID {
		return nil, fmt.Errorf("%w: expected_assistant_program_id must match this template", ErrInvalidUserSetupQuest)
	}
	eligibility := EvaluateUserSetupQuestEligibility(template)
	if !eligibility.Eligible {
		return nil, fmt.Errorf("%w: template prerequisites are incomplete", ErrInvalidUserSetupQuest)
	}
	return quest, nil
}

// EvaluateUserSetupQuestEligibility checks only portable target prerequisites.
// Integration installation/readiness remains a canonical runtime owner and is
// deliberately not inspected here.
func EvaluateUserSetupQuestEligibility(template Template) UserSetupQuestEligibility {
	result := UserSetupQuestEligibility{Eligible: true}
	add := func(code, message string) {
		result.Eligible = false
		result.Missing = append(result.Missing, UserSetupQuestEligibilityDiagnostic{Code: code, Message: message})
	}
	if template.Builtin || template.PluginOwner != nil {
		add("user_owned_template_required", "Setup quests can be authored only on a user-owned template.")
	}
	if !userSetupQuestIDPattern.MatchString(template.ID) {
		add("stable_template_id_required", "The template folder ID must be a lower-case stable ID of at most 64 characters.")
	}
	if template.ProjectConnection == nil || template.HasInvalidProjectConnection() {
		add("project_connection_required", "Add a valid project_connection declaration with an existing- or new-project mode.")
	} else if !hasConstructibleUserQuestMode(template) {
		add("constructible_project_required", "The connection needs an attach extension or a real skeleton and matching project entry file.")
	}
	if template.AssistantProgram == nil || template.HasInvalidAssistantProgram() || template.AssistantProgram.SchemaVersion != workspace.AssistantProgramSchemaVersion {
		add("assistant_program_required", "Add a valid current Assistant Program with required Home and project roles.")
	}
	fileOnly := false
	if template.RuntimeRequirements != nil && !template.HasInvalidRuntimeRequirements() {
		for _, mode := range template.RuntimeRequirements.OperatingModes {
			fileOnly = fileOnly || mode.ID == "file_only" && len(mode.Requires) == 0
		}
	}
	if !fileOnly {
		add("file_only_runtime_required", "Add a file_only operating mode that requires no live runtime access.")
	}
	runtimeMode := false
	if template.SetupWizard != nil && !template.HasInvalidSetupWizard() {
		for _, step := range template.SetupWizard.Steps {
			runtimeMode = runtimeMode || step.Kind == workspace.SetupStepKindRuntimeMode && step.Required
		}
	}
	if !runtimeMode {
		add("runtime_mode_wizard_required", "Add a valid post-workspace setup_wizard with a required runtime_mode step.")
	}
	return result
}

func hasConstructibleUserQuestMode(template Template) bool {
	if template.ProjectConnection == nil {
		return false
	}
	if template.ProjectConnection.Supports(ProjectConnectionExistingProject) && template.ProjectConnection.AttachExisting != nil && len(template.ProjectConnection.AttachExisting.EntryExtensions) > 0 {
		return true
	}
	if !template.ProjectConnection.Supports(ProjectConnectionNewProject) || !template.HasSkeleton || template.ProjectEntry == nil {
		return false
	}
	files, err := PreviewInstantiation(template, "eligibility-check")
	if err != nil {
		return false
	}
	entry, err := ResolveProjectEntryForName(template, "eligibility-check")
	if err != nil || entry == "" {
		return false
	}
	if template.ProjectConnection.AttachExisting == nil {
		return true
	}
	allowed := make(map[string]struct{}, len(template.ProjectConnection.AttachExisting.EntryExtensions))
	for _, extension := range template.ProjectConnection.AttachExisting.EntryExtensions {
		allowed[extension] = struct{}{}
	}
	matches := 0
	for _, file := range files {
		if _, ok := allowed[strings.ToLower(filepath.Ext(file))]; ok {
			matches++
		}
	}
	_, entryAllowed := allowed[strings.ToLower(filepath.Ext(entry))]
	return entryAllowed && matches == 1
}

// NewUserSetupQuest turns one bounded draft into the persisted strict shape.
// Existing identities are retained on edit; blank creation gets fresh host IDs.
func NewUserSetupQuest(template Template, current *UserSetupQuest, draft UserSetupQuestDraft) (*UserSetupQuest, error) {
	if !EvaluateUserSetupQuestEligibility(template).Eligible {
		return nil, fmt.Errorf("%w: template prerequisites are incomplete", ErrInvalidUserSetupQuest)
	}
	attachmentID := "uqatt_" + strings.ReplaceAll(uuid.NewString(), "-", "")[:24]
	questID := "quest_" + strings.ReplaceAll(uuid.NewString(), "-", "")[:24]
	stepIDs := make([]string, specialist.SetupJourneyRequiredSteps)
	for index := range stepIDs {
		stepIDs[index] = "step_" + strings.ReplaceAll(uuid.NewString(), "-", "")[:20]
	}
	if current != nil && current.Declaration != nil {
		attachmentID = current.AttachmentID
		questID = current.Declaration.ID
		if len(current.Declaration.Steps) != specialist.SetupJourneyRequiredSteps {
			return nil, fmt.Errorf("%w: current declaration is malformed", ErrInvalidUserSetupQuest)
		}
		for index := range stepIDs {
			stepIDs[index] = current.Declaration.Steps[index].ID
		}
	}
	if len(draft.Steps) != specialist.SetupJourneyRequiredSteps {
		return nil, fmt.Errorf("%w: exactly five fixed steps are required", ErrInvalidUserSetupQuest)
	}
	kinds := []specialist.SetupStepKind{
		specialist.SetupStepIntegrationInstall,
		specialist.SetupStepProjectConnect,
		specialist.SetupStepWorkspaceSetup,
		specialist.SetupStepAssistantProgramStaffing,
		specialist.SetupStepSummary,
	}
	steps := make([]specialist.SetupJourneyStep, len(kinds))
	for index, kind := range kinds {
		if draft.Steps[index].Kind != kind {
			return nil, fmt.Errorf("%w: step %d kind must be %q", ErrInvalidUserSetupQuest, index, kind)
		}
		steps[index] = specialist.SetupJourneyStep{ID: stepIDs[index], Kind: kind, Title: draft.Steps[index].Title, Description: draft.Steps[index].Description}
	}
	declaration, err := specialist.NormalizeSetupJourney(specialist.SetupJourney{
		SchemaVersion: specialist.SetupJourneySchemaVersion, Version: 1, ID: questID,
		Title: draft.Title, Description: draft.Description, IntegrationKey: draft.IntegrationKey,
		ExpectedBlueprintID: template.ID, ExpectedAssistantProgramID: template.AssistantProgram.ID,
		Steps: steps, WorkspaceLaunch: cloneUserQuestLaunch(draft.WorkspaceLaunch),
	})
	if err != nil || declaration.WorkspaceLaunch == nil {
		if err == nil {
			err = errors.New("workspace_launch is required")
		}
		return nil, fmt.Errorf("%w: %v", ErrInvalidUserSetupQuest, err)
	}
	return &UserSetupQuest{AttachmentID: attachmentID, Declaration: declaration}, nil
}

func UserSetupQuestRevision(quest *UserSetupQuest) string {
	if quest == nil {
		return digestUserQuestBytes([]byte("user_setup_quest:absent:v1"))
	}
	encoded, err := json.Marshal(quest)
	if err != nil {
		return ""
	}
	return digestUserQuestBytes(encoded)
}

func UserSetupQuestDefinitionDigest(quest *UserSetupQuest) string {
	return UserSetupQuestRevision(quest)
}

// UserSetupQuestExecutionDigest binds every normalized target field consumed by
// canonical project/runtime/staffing owners. Display-only template metadata and
// the ordinary Agents roster are intentionally excluded.
func UserSetupQuestExecutionDigest(template Template) string {
	type executionReferences struct {
		TemplateID             string                                 `json:"template_id"`
		AttachmentID           string                                 `json:"attachment_id"`
		SkeletonDigest         string                                 `json:"skeleton_digest"`
		AssistantProgram       *workspace.AssistantProgramDeclaration `json:"assistant_program"`
		ProjectEntry           *ProjectEntry                          `json:"project_entry"`
		ProjectConnection      *ProjectConnectionDeclaration          `json:"project_connection"`
		RuntimeRequirements    *RuntimeRequirementsContract           `json:"runtime_requirements"`
		SetupWizard            *SetupWizard                           `json:"setup_wizard"`
		StarterTasks           []StarterTask                          `json:"starter_tasks,omitempty"`
		DirectoryRequirements  []DirectoryRequirement                 `json:"directory_requirements,omitempty"`
		AutomationRecipes      []AutomationRecipe                     `json:"automation_recipes,omitempty"`
		CapabilityRequirements []CapabilityRequirement                `json:"capability_requirements,omitempty"`
		Tools                  ToolDefaults                           `json:"tools"`
		Capabilities           []CapabilityInstall                    `json:"capabilities,omitempty"`
	}
	attachmentID := ""
	if template.UserSetupQuest != nil {
		attachmentID = template.UserSetupQuest.AttachmentID
	}
	encoded, err := json.Marshal(executionReferences{
		TemplateID: template.ID, AttachmentID: attachmentID, SkeletonDigest: userQuestSkeletonDigest(template), AssistantProgram: template.AssistantProgram,
		ProjectEntry: template.ProjectEntry, ProjectConnection: template.ProjectConnection,
		RuntimeRequirements: template.RuntimeRequirements, SetupWizard: template.SetupWizard,
		StarterTasks: template.StarterTasks, DirectoryRequirements: template.DirectoryRequirements,
		AutomationRecipes: template.AutomationRecipes, CapabilityRequirements: template.CapabilityRequirements,
		Tools: template.Tools, Capabilities: template.Capabilities,
	})
	if err != nil {
		return ""
	}
	return digestUserQuestBytes(encoded)
}

func userQuestSkeletonDigest(template Template) string {
	if !template.HasSkeleton || strings.TrimSpace(template.Path) == "" {
		return digestUserQuestBytes([]byte("skeleton:absent:v1"))
	}
	type fileIdentity struct {
		Path    string `json:"path"`
		Mode    uint32 `json:"mode"`
		Content string `json:"content"`
	}
	files := make([]fileIdentity, 0)
	root := template.Path
	err := fs.WalkDir(os.DirFS(root), ".", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "." || path == ManifestFileName || entry.Type()&fs.ModeSymlink != 0 {
			return nil
		}
		if path == DashboardDirName && entry.IsDir() {
			return fs.SkipDir
		}
		if entry.IsDir() {
			return nil
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path))) // #nosec G304 -- path is emitted by WalkDir under the normalized skeleton root
		if err != nil {
			return err
		}
		files = append(files, fileIdentity{Path: filepath.ToSlash(path), Mode: uint32(info.Mode().Perm()), Content: digestUserQuestBytes(content)})
		return nil
	})
	if err != nil {
		return ""
	}
	encoded, err := json.Marshal(files)
	if err != nil {
		return ""
	}
	return digestUserQuestBytes(encoded)
}

func userSetupQuestDraft(quest *UserSetupQuest) UserSetupQuestDraft {
	if quest == nil || quest.Declaration == nil {
		return UserSetupQuestDraft{}
	}
	d := quest.Declaration
	steps := make([]UserSetupQuestStepDraft, len(d.Steps))
	for index, step := range d.Steps {
		steps[index] = UserSetupQuestStepDraft{Kind: step.Kind, Title: step.Title, Description: step.Description}
	}
	return UserSetupQuestDraft{Title: d.Title, Description: d.Description, IntegrationKey: d.IntegrationKey, Steps: steps, WorkspaceLaunch: cloneUserQuestLaunch(d.WorkspaceLaunch)}
}

func defaultUserSetupQuestDraft() UserSetupQuestDraft {
	return UserSetupQuestDraft{
		Title: "Set up this project", Description: "Connect a project and choose how Ori can help.", IntegrationKey: "reviewed_integration",
		WorkspaceLaunch: &specialist.WorkspaceLaunchCopy{
			GroupTitle: "Create a Home for these projects", GroupName: "My projects",
			RuntimeTitle: "Choose how Ori works", RuntimeInstructions: "File-only remains available. Live application control is optional and must be configured for the exact project later.",
		},
		Steps: []UserSetupQuestStepDraft{
			{Kind: specialist.SetupStepIntegrationInstall, Title: "Check the integration", Description: "Review the required host-approved integration before installing or enabling it."},
			{Kind: specialist.SetupStepProjectConnect, Title: "Connect a project", Description: "Choose an existing project or create a new one after reviewing the exact files."},
			{Kind: specialist.SetupStepWorkspaceSetup, Title: "Choose how Ori works", Description: "Choose File-only or finish an available live setup in the project's Setup Wizard."},
			{Kind: specialist.SetupStepAssistantProgramStaffing, Title: "Staff the project", Description: "Review separate Home and exact-project roles before creating or assigning agents."},
			{Kind: specialist.SetupStepSummary, Title: "Review setup", Description: "Review what is connected, staffed, selected, and still optional."},
		},
	}
}

func cloneUserQuestLaunch(source *specialist.WorkspaceLaunchCopy) *specialist.WorkspaceLaunchCopy {
	if source == nil {
		return nil
	}
	clone := *source
	return &clone
}

func digestUserQuestBytes(value []byte) string {
	sum := sha256.Sum256(value)
	return hex.EncodeToString(sum[:])
}
