// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface check
var _ pluginapi.PluginTool = (*minimal_pluginTool)(nil)

// MinimalPluginParams represents the parameters for this plugin
type MinimalPluginParams struct {
	Operation string `json:"operation"` // Operation to perform: echo (returns input) or status (returns plugin status)
	Message   string `json:"message"`   // Message to echo (required for echo operation)
	Count     int    `json:"count"`     // Number of times to repeat the message (for echo operation)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *minimal_pluginTool) Call(ctx context.Context, args string) (string, error) {
	var params MinimalPluginParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.Operation == "" {
		return "", fmt.Errorf("required field 'operation' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
