// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*minimal_pluginTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool          = (*minimal_pluginTool)(nil)
	_ pluginapi.MetadataProvider       = (*minimal_pluginTool)(nil)
	_ pluginapi.PluginCompatibility    = (*minimal_pluginTool)(nil)
	_ pluginapi.InitializationProvider = (*minimal_pluginTool)(nil)
)

// MinimalPluginParams represents the parameters for this plugin
type MinimalPluginParams struct {
	Operation string `json:"operation"` // Operation to perform: echo (returns input) or status (returns plugin status)
	Message   string `json:"message"`   // Message to echo
	Count     int    `json:"count"`     // Number of times to repeat the message
}

// OperationHandler is a function that handles a specific operation
type OperationHandler func(ctx context.Context, t *minimal_pluginTool, params *MinimalPluginParams) (string, error)

// operationRegistry maps operation names to their handler functions
// Handler functions must be defined by you with the naming convention handle{PascalCase}
var operationRegistry = map[string]OperationHandler{
	"echo":   handleEcho,
	"status": handleStatus,
}

// Execute dispatches to the appropriate operation handler
// This method is auto-generated from plugin.yaml operations
func (t *minimal_pluginTool) Execute(ctx context.Context, params *MinimalPluginParams) (string, error) {
	handler, ok := operationRegistry[params.Operation]
	if !ok {
		return "", fmt.Errorf("unknown operation: %s. Valid operations: echo, status", params.Operation)
	}
	return handler(ctx, t, params)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *minimal_pluginTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params MinimalPluginParams

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method
	return t.Execute(ctx, &params)
}

// GetRequiredConfig returns the configuration variables needed by this plugin
// This method is auto-generated from plugin.yaml config section
func (t *minimal_pluginTool) GetRequiredConfig() []pluginapi.ConfigVariable {
	return t.GetConfigFromYAML()
}

// ValidateConfig validates the provided configuration
// This method is auto-generated from plugin.yaml config section
func (t *minimal_pluginTool) ValidateConfig(config map[string]interface{}) error {
	// Validate api_endpoint (required)
	if val, ok := config["api_endpoint"]; !ok || val == nil || val == "" {
		return fmt.Errorf("api_endpoint is required")
	}
	return nil
}

// InitializeWithConfig initializes the plugin with the provided configuration
// This method is auto-generated from plugin.yaml config section
func (t *minimal_pluginTool) InitializeWithConfig(config map[string]interface{}) error {
	sm := t.Settings()
	if sm == nil {
		return fmt.Errorf("settings manager not available")
	}
	for key, value := range config {
		if err := sm.Set(key, value); err != nil {
			return fmt.Errorf("failed to store config %s: %w", key, err)
		}
	}
	return nil
}
