// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*minimal_pluginTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool          = (*minimal_pluginTool)(nil)
	_ pluginapi.MetadataProvider       = (*minimal_pluginTool)(nil)
	_ pluginapi.PluginCompatibility    = (*minimal_pluginTool)(nil)
	_ pluginapi.InitializationProvider = (*minimal_pluginTool)(nil)
)

// MinimalPluginParams represents the parameters for this plugin
type MinimalPluginParams struct {
	Operation string `json:"operation"` // Operation to perform: echo (returns input) or status (returns plugin status)
	Message   string `json:"message"`   // Message to echo
	Count     int    `json:"count"`     // Number of times to repeat the message
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *minimal_pluginTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params MinimalPluginParams

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
