// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface check
var _ pluginapi.PluginTool = (*webapp_pluginTool)(nil)

// WebappPluginParams represents the parameters for this plugin
type WebappPluginParams struct {
	Operation       string `json:"operation"`        // Operation to perform
	ItemName        string `json:"item_name"`        // Name of the item (for add_item and delete_item operations)
	ItemDescription string `json:"item_description"` // Description of the item (for add_item operation)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *webapp_pluginTool) Call(ctx context.Context, args string) (string, error) {
	var params WebappPluginParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.Operation == "" {
		return "", fmt.Errorf("required field 'operation' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
