// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"embed"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*WebappPluginTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool          = (*WebappPluginTool)(nil)
	_ pluginapi.MetadataProvider       = (*WebappPluginTool)(nil)
	_ pluginapi.PluginCompatibility    = (*WebappPluginTool)(nil)
	_ pluginapi.InitializationProvider = (*WebappPluginTool)(nil)
	_ pluginapi.WebPageProvider        = (*WebappPluginTool)(nil)
)

//go:embed plugin.yaml
var configYAML string

//go:embed templates
var templatesFS embed.FS

// Params represents the parameters for this plugin
type Params struct {
	Operation       string `json:"operation"`        // Operation to perform
	ItemName        string `json:"item_name"`        // Name of the item (for add_item and delete_item operations)
	ItemDescription string `json:"item_description"` // Description of the item (for add_item operation)
}

// OperationHandler is a function that handles a specific operation
type OperationHandler func(ctx context.Context, t *WebappPluginTool, params *Params) (string, error)

// operationRegistry maps operation names to their handler functions
// Handler functions must be defined by you with the naming convention handle{PascalCase}
var operationRegistry = map[string]OperationHandler{
	"add_item":       handleAddItem,
	"delete_item":    handleDeleteItem,
	"list_items":     handleListItems,
	"open_dashboard": handleOpenDashboard,
}

// Execute dispatches to the appropriate operation handler
// This method is auto-generated from plugin.yaml operations
func (t *WebappPluginTool) Execute(ctx context.Context, params *Params) (string, error) {
	handler, ok := operationRegistry[params.Operation]
	if !ok {
		return "", fmt.Errorf("unknown operation: %s. Valid operations: add_item, delete_item, list_items, open_dashboard", params.Operation)
	}
	return handler(ctx, t, params)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *WebappPluginTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params Params

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method
	return t.Execute(ctx, &params)
}

// GetRequiredConfig returns the configuration variables needed by this plugin
// This method is auto-generated from plugin.yaml config section
func (t *WebappPluginTool) GetRequiredConfig() []pluginapi.ConfigVariable {
	return t.GetConfigFromYAML()
}

// ValidateConfig validates the provided configuration
// This method is auto-generated from plugin.yaml config section
func (t *WebappPluginTool) ValidateConfig(config map[string]interface{}) error {
	return nil
}

// InitializeWithConfig initializes the plugin with the provided configuration
// This method is auto-generated from plugin.yaml config section
func (t *WebappPluginTool) InitializeWithConfig(config map[string]interface{}) error {
	sm := t.Settings()
	if sm == nil {
		return fmt.Errorf("settings manager not available")
	}
	for key, value := range config {
		if err := sm.Set(key, value); err != nil {
			return fmt.Errorf("failed to store config %s: %w", key, err)
		}
	}
	return nil
}

// GetWebPages returns the available web pages for this plugin
// This method is auto-generated from plugin.yaml web_pages section
func (t *WebappPluginTool) GetWebPages() []string {
	return []string{
		"dashboard",
	}
}

// WebPageHandler is a function that serves a specific web page
type WebPageHandler func(t *WebappPluginTool, query map[string]string) (string, string, error)

// webPageRegistry maps page paths to their handler functions
// Handler functions must be defined by you with the naming convention serve{PascalCase}Page
var webPageRegistry = map[string]WebPageHandler{
	"dashboard": serveDashboardPage,
}

// ServeWebPage dispatches to the appropriate page handler
// This method is auto-generated from plugin.yaml web_pages section
func (t *WebappPluginTool) ServeWebPage(path string, query map[string]string) (string, string, error) {
	handler, ok := webPageRegistry[path]
	if !ok {
		return "", "", fmt.Errorf("page not found: %s", path)
	}
	return handler(t, query)
}
