package specialist

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"regexp"
	"strings"
	"unicode"
	"unicode/utf8"
)

const (
	// SetupJourneySchemaVersion is the only declaration schema this build can
	// expose. Declaration Version is revisioned independently within the schema.
	SetupJourneySchemaVersion = 1

	MaxSetupJourneyBytes      = 16 << 10
	MaxSetupJourneyIDBytes    = 64
	MaxSetupJourneyTitleBytes = 200
	MaxSetupJourneyTextBytes  = 2_000
	MaxSetupJourneyVersion    = 1_000_000
	// SetupJourneyRequiredSteps is the step count of the specialist shape, the
	// only shape plugins and user templates may author.
	SetupJourneyRequiredSteps = 5
)

// SetupStepKind selects one closed host-owned setup primitive. It never names
// an adapter, route, command, source, or executable implementation.
type SetupStepKind string

const (
	SetupStepIntegrationInstall       SetupStepKind = "integration_install"
	SetupStepProjectConnect           SetupStepKind = "project_connect"
	SetupStepWorkspaceSetup           SetupStepKind = "workspace_setup"
	SetupStepAssistantProgramStaffing SetupStepKind = "assistant_program_staffing"
	SetupStepSummary                  SetupStepKind = "summary"

	// Host-owned account-link primitives. They are compiled into Ori like the
	// specialist kinds and are not authorable by plugins or user templates.
	SetupStepWorkspaceCreate SetupStepKind = "workspace_create"
	SetupStepAccountConnect  SetupStepKind = "account_connect"
	SetupStepAccountLink     SetupStepKind = "account_link"
)

// SetupJourneyShape names one compiled ordered step-kind sequence. A shape is
// inferred from a declaration's steps; no declaration field can select one.
type SetupJourneyShape string

const (
	SetupJourneyShapeSpecialist  SetupJourneyShape = "specialist"
	SetupJourneyShapeAccountLink SetupJourneyShape = "account_link"
	// SetupJourneyShapeIntegrationInstall is generated by the host from the
	// reviewed-integration registry. No plugin or template authors it.
	SetupJourneyShapeIntegrationInstall SetupJourneyShape = "integration_install"
)

var setupJourneyStepOrder = [...]SetupStepKind{
	SetupStepIntegrationInstall,
	SetupStepProjectConnect,
	SetupStepWorkspaceSetup,
	SetupStepAssistantProgramStaffing,
	SetupStepSummary,
}

var integrationInstallStepOrder = [...]SetupStepKind{
	SetupStepIntegrationInstall,
	SetupStepSummary,
}

var accountLinkStepOrder = [...]SetupStepKind{
	SetupStepWorkspaceCreate,
	SetupStepAccountConnect,
	SetupStepAccountLink,
	SetupStepSummary,
}

// compiledSetupJourneyShapes lists every shape in the order Shape tries them.
var compiledSetupJourneyShapes = [...]SetupJourneyShape{
	SetupJourneyShapeSpecialist,
	SetupJourneyShapeIntegrationInstall,
	SetupJourneyShapeAccountLink,
}

// SetupJourneyShapeSteps returns a copy of a compiled shape's ordered kinds, or
// nil for an unknown shape.
func SetupJourneyShapeSteps(shape SetupJourneyShape) []SetupStepKind {
	switch shape {
	case SetupJourneyShapeSpecialist:
		return append([]SetupStepKind(nil), setupJourneyStepOrder[:]...)
	case SetupJourneyShapeIntegrationInstall:
		return append([]SetupStepKind(nil), integrationInstallStepOrder[:]...)
	case SetupJourneyShapeAccountLink:
		return append([]SetupStepKind(nil), accountLinkStepOrder[:]...)
	default:
		return nil
	}
}

// SetupStepKinds returns every compiled step kind across all shapes, once each,
// in a fixed order. Host registries use it to prove they cover the closed set.
func SetupStepKinds() []SetupStepKind {
	kinds := append([]SetupStepKind(nil), setupJourneyStepOrder[:]...)
	for _, kind := range accountLinkStepOrder {
		if kind != SetupStepSummary {
			kinds = append(kinds, kind)
		}
	}
	return kinds
}

// Shape reports which compiled shape the declaration's step kinds match
// position by position, or "" when they match none.
func (j *SetupJourney) Shape() SetupJourneyShape {
	if j == nil {
		return ""
	}
	for _, shape := range compiledSetupJourneyShapes {
		expected := SetupJourneyShapeSteps(shape)
		if len(j.Steps) != len(expected) {
			continue
		}
		matches := true
		for index, step := range j.Steps {
			matches = matches && step.Kind == expected[index]
		}
		if matches {
			return shape
		}
	}
	return ""
}

// candidateSetupJourneyShape picks which compiled sequence a declaration is
// checked against. It only selects error text and expectations: acceptance
// still requires an exact positional match. The specialist and install shapes
// share a first kind but differ in length, so both first kind and step count
// select between them; no declaration can match two shapes.
func candidateSetupJourneyShape(steps []SetupJourneyStep) SetupJourneyShape {
	if len(steps) == 0 {
		return SetupJourneyShapeSpecialist
	}
	switch SetupStepKind(normalizeSetupJourneyID(string(steps[0].Kind))) {
	case SetupStepWorkspaceCreate:
		return SetupJourneyShapeAccountLink
	case SetupStepIntegrationInstall:
		if len(steps) == len(integrationInstallStepOrder) {
			return SetupJourneyShapeIntegrationInstall
		}
	}
	return SetupJourneyShapeSpecialist
}

// SetupJourney is bounded inert discovery data. Behavior for each step kind is
// compiled into the host; no declaration field can select executable behavior.
type SetupJourney struct {
	// OwnerPluginID is runtime-only binding metadata. It cannot be authored in
	// JSON and never authorizes an action by itself.
	OwnerPluginID              string               `json:"-"`
	SchemaVersion              int                  `json:"schema_version"`
	Version                    int                  `json:"version"`
	ID                         string               `json:"id"`
	Title                      string               `json:"title"`
	Description                string               `json:"description"`
	IntegrationKey             string               `json:"integration_key"`
	ExpectedBlueprintID        string               `json:"expected_blueprint_id"`
	ExpectedAssistantProgramID string               `json:"expected_assistant_program_id"`
	Steps                      []SetupJourneyStep   `json:"steps"`
	WorkspaceLaunch            *WorkspaceLaunchCopy `json:"workspace_launch,omitempty"`
}

// WorkspaceLaunchCopy describes the four first-run screens. Canonical project,
// runtime and staffing readiness remain independently owned by the five steps.
// These labels and instructions cannot select a command, route or adapter.
type WorkspaceLaunchCopy struct {
	GroupTitle          string `json:"group_title"`
	GroupName           string `json:"group_name"`
	RuntimeTitle        string `json:"runtime_title"`
	RuntimeInstructions string `json:"runtime_instructions"`
}

// SetupJourneyStep is one display-only item in its shape's fixed order.
type SetupJourneyStep struct {
	ID          string        `json:"id"`
	Kind        SetupStepKind `json:"kind"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
}

// ParseSetupJourney strictly decodes and normalizes one declaration. It is
// exported so fixtures and future trusted import boundaries use the same
// fail-closed contract as built-in declarations.
func ParseSetupJourney(data []byte) (*SetupJourney, error) {
	if len(data) == 0 {
		return nil, errors.New("setup journey declaration is empty")
	}
	if len(data) > MaxSetupJourneyBytes {
		return nil, fmt.Errorf("setup journey declaration exceeds %d bytes", MaxSetupJourneyBytes)
	}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var declaration SetupJourney
	if err := decoder.Decode(&declaration); err != nil {
		return nil, fmt.Errorf("decode setup journey declaration: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return nil, errors.New("setup journey declaration contains trailing data")
		}
		return nil, fmt.Errorf("decode setup journey declaration trailing data: %w", err)
	}
	return NormalizeSetupJourney(declaration)
}

// NormalizeSetupJourney validates a compiled declaration and returns an
// independent normalized copy. It deliberately round-trips through JSON for
// the same serialized-size bound used by ParseSetupJourney.
func NormalizeSetupJourney(declaration SetupJourney) (*SetupJourney, error) {
	encoded, err := json.Marshal(declaration)
	if err != nil {
		return nil, fmt.Errorf("encode setup journey declaration: %w", err)
	}
	if len(encoded) > MaxSetupJourneyBytes {
		return nil, fmt.Errorf("setup journey declaration exceeds %d bytes", MaxSetupJourneyBytes)
	}

	declaration.ID = normalizeSetupJourneyID(declaration.ID)
	declaration.IntegrationKey = normalizeSetupJourneyID(declaration.IntegrationKey)
	declaration.ExpectedBlueprintID = normalizeSetupJourneyID(declaration.ExpectedBlueprintID)
	declaration.ExpectedAssistantProgramID = normalizeSetupJourneyID(declaration.ExpectedAssistantProgramID)
	declaration.Title = strings.TrimSpace(declaration.Title)
	declaration.Description = strings.TrimSpace(declaration.Description)

	if declaration.SchemaVersion != SetupJourneySchemaVersion {
		return nil, fmt.Errorf("setup journey schema_version must be %d", SetupJourneySchemaVersion)
	}
	if declaration.Version < 1 || declaration.Version > MaxSetupJourneyVersion {
		return nil, fmt.Errorf("setup journey version must be between 1 and %d", MaxSetupJourneyVersion)
	}
	if err := validateSetupJourneyID("id", declaration.ID); err != nil {
		return nil, err
	}
	if err := validateSetupJourneyText("title", declaration.Title, MaxSetupJourneyTitleBytes); err != nil {
		return nil, err
	}
	if err := validateSetupJourneyText("description", declaration.Description, MaxSetupJourneyTextBytes); err != nil {
		return nil, err
	}
	shape := candidateSetupJourneyShape(declaration.Steps)
	expectedKinds := SetupJourneyShapeSteps(shape)
	switch shape {
	case SetupJourneyShapeAccountLink:
		// Host account-link quests target one built-in template and carry no
		// integration or Assistant Program. Built-in membership is checked by the
		// host catalog, which can see the template library without an import cycle.
		if err := validateSetupJourneyID("expected_blueprint_id", declaration.ExpectedBlueprintID); err != nil {
			return nil, err
		}
		for field, value := range map[string]string{
			"integration_key":               declaration.IntegrationKey,
			"expected_assistant_program_id": declaration.ExpectedAssistantProgramID,
		} {
			if value != "" {
				return nil, fmt.Errorf("setup journey %s must be empty for the %s shape", field, shape)
			}
		}
		if declaration.WorkspaceLaunch != nil {
			return nil, fmt.Errorf("setup journey workspace_launch is not allowed for the %s shape", shape)
		}
		if len(declaration.Steps) != len(expectedKinds) {
			return nil, fmt.Errorf("setup journey must contain exactly %d steps for the %s shape", len(expectedKinds), shape)
		}
	case SetupJourneyShapeIntegrationInstall:
		// The host generates one install quest per reviewed integration. It
		// carries the integration's references so the install step can verify
		// the plugin, and it never launches a workspace.
		for field, value := range map[string]string{
			"integration_key":               declaration.IntegrationKey,
			"expected_blueprint_id":         declaration.ExpectedBlueprintID,
			"expected_assistant_program_id": declaration.ExpectedAssistantProgramID,
		} {
			if err := validateSetupJourneyID(field, value); err != nil {
				return nil, err
			}
		}
		if declaration.WorkspaceLaunch != nil {
			return nil, fmt.Errorf("setup journey workspace_launch is not allowed for the %s shape", shape)
		}
		if len(declaration.Steps) != len(expectedKinds) {
			return nil, fmt.Errorf("setup journey must contain exactly %d steps for the %s shape", len(expectedKinds), shape)
		}
	default:
		for field, value := range map[string]string{
			"integration_key":               declaration.IntegrationKey,
			"expected_blueprint_id":         declaration.ExpectedBlueprintID,
			"expected_assistant_program_id": declaration.ExpectedAssistantProgramID,
		} {
			if err := validateSetupJourneyID(field, value); err != nil {
				return nil, err
			}
		}
		if len(declaration.Steps) != SetupJourneyRequiredSteps {
			return nil, fmt.Errorf("setup journey must contain exactly %d steps", SetupJourneyRequiredSteps)
		}
	}

	seenIDs := make(map[string]struct{}, len(declaration.Steps))
	steps := make([]SetupJourneyStep, len(declaration.Steps))
	for index := range declaration.Steps {
		step := declaration.Steps[index]
		step.ID = normalizeSetupJourneyID(step.ID)
		step.Kind = SetupStepKind(normalizeSetupJourneyID(string(step.Kind)))
		step.Title = strings.TrimSpace(step.Title)
		step.Description = strings.TrimSpace(step.Description)

		if err := validateSetupJourneyID(fmt.Sprintf("steps[%d].id", index), step.ID); err != nil {
			return nil, err
		}
		if _, duplicate := seenIDs[step.ID]; duplicate {
			return nil, fmt.Errorf("setup journey step id %q is duplicated", step.ID)
		}
		seenIDs[step.ID] = struct{}{}
		if step.Kind != expectedKinds[index] {
			return nil, fmt.Errorf("setup journey step %d kind must be %q", index, expectedKinds[index])
		}
		if err := validateSetupJourneyText(fmt.Sprintf("steps[%d].title", index), step.Title, MaxSetupJourneyTitleBytes); err != nil {
			return nil, err
		}
		if err := validateSetupJourneyText(fmt.Sprintf("steps[%d].description", index), step.Description, MaxSetupJourneyTextBytes); err != nil {
			return nil, err
		}
		steps[index] = step
	}
	declaration.Steps = steps
	if declaration.WorkspaceLaunch != nil {
		copy := *declaration.WorkspaceLaunch
		for field, value := range map[string]*string{"group_title": &copy.GroupTitle, "group_name": &copy.GroupName, "runtime_title": &copy.RuntimeTitle, "runtime_instructions": &copy.RuntimeInstructions} {
			*value = strings.TrimSpace(*value)
			if err := validateSetupJourneyText(field, *value, 1000); err != nil {
				return nil, err
			}
		}
		declaration.WorkspaceLaunch = &copy
	}
	return &declaration, nil
}

var setupJourneyIDPattern = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]{0,63}$`)

func normalizeSetupJourneyID(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}

func validateSetupJourneyID(field, value string) error {
	if len(value) == 0 || len(value) > MaxSetupJourneyIDBytes || !setupJourneyIDPattern.MatchString(value) {
		return fmt.Errorf("setup journey %s must be a lower-case stable id of at most %d bytes", field, MaxSetupJourneyIDBytes)
	}
	return nil
}

// ValidateSetupJourneyText applies the quest-copy plain-text rules to host data
// that feeds a generated declaration: required, bounded UTF-8, and free of
// markup, URLs and control characters. The value must already be trimmed.
func ValidateSetupJourneyText(field, value string, maxBytes int) error {
	return validateSetupJourneyText(field, value, maxBytes)
}

func validateSetupJourneyText(field, value string, maxBytes int) error {
	if value == "" {
		return fmt.Errorf("setup journey %s is required", field)
	}
	if !utf8.ValidString(value) || len(value) > maxBytes {
		return fmt.Errorf("setup journey %s must be valid UTF-8 of at most %d bytes", field, maxBytes)
	}
	lower := strings.ToLower(value)
	if strings.ContainsAny(value, "<>`*") || strings.Contains(value, "](") || strings.Contains(value, "![") ||
		strings.Contains(lower, "://") || strings.Contains(lower, "www.") ||
		strings.Contains(lower, "javascript:") || strings.Contains(lower, "data:") ||
		strings.Contains(lower, "file:") || strings.Contains(lower, "mailto:") ||
		strings.Contains(lower, "http:") || strings.Contains(lower, "https:") {
		return fmt.Errorf("setup journey %s must contain plain display text only", field)
	}
	for _, r := range value {
		if (unicode.IsControl(r) && r != '\n' && r != '\t') || unicode.In(r, unicode.Cf) {
			return fmt.Errorf("setup journey %s contains a disallowed control character", field)
		}
	}
	return nil
}

func mustNormalizeRegistry(entries []Entry) []Entry {
	registry := make([]Entry, len(entries))
	for index := range entries {
		registry[index] = cloneEntry(entries[index])
		if registry[index].SetupJourney == nil {
			continue
		}
		normalized, err := NormalizeSetupJourney(*registry[index].SetupJourney)
		if err != nil {
			panic(fmt.Sprintf("invalid built-in specialist setup journey for %q: %v", registry[index].Slug, err))
		}
		registry[index].SetupJourney = normalized
	}
	return registry
}

func cloneSetupJourney(source *SetupJourney) *SetupJourney {
	if source == nil {
		return nil
	}
	clone := *source
	clone.Steps = append([]SetupJourneyStep(nil), source.Steps...)
	if source.WorkspaceLaunch != nil {
		copy := *source.WorkspaceLaunch
		clone.WorkspaceLaunch = &copy
	}
	return &clone
}
