package workspaceplan

import (
	"fmt"
	"strings"
)

// Planning artifacts are rendered from typed Plan content by application
// templates, not written by a model (FR-95, FR-96).
//
// That matters for a reason beyond tidiness: an approved plan and the document
// describing it must say the same thing. If a model wrote the PRD, the file and
// the approved structure could disagree, and only one of them creates work.
// Rendering deterministically means the document is always a faithful
// projection of what was approved.

// ArtifactRenderer turns one proposed artifact into its file content.
type ArtifactRenderer interface {
	Render(artifact ProposedArtifact, plan *Plan, version *Version) ([]byte, error)
}

// DefaultArtifactRenderer renders the built-in artifact kinds.
type DefaultArtifactRenderer struct{}

var _ ArtifactRenderer = DefaultArtifactRenderer{}

// Render produces deterministic Markdown for a proposed artifact. The same
// approved version always renders byte-identical output, so re-running a
// materialization cannot produce a different document.
func (DefaultArtifactRenderer) Render(artifact ProposedArtifact, plan *Plan, version *Version) ([]byte, error) {
	if plan == nil || version == nil {
		return nil, fmt.Errorf("%w: rendering requires a plan and a version", ErrValidation)
	}

	switch artifact.Kind {
	case ArtifactPRD:
		return []byte(renderPRD(artifact, plan, version)), nil
	case ArtifactTaskList:
		return []byte(renderTaskList(artifact, plan, version)), nil
	case ArtifactNote, ArtifactDocument:
		return []byte(renderNote(artifact, plan, version)), nil
	default:
		return nil, fmt.Errorf("%w: unsupported artifact kind %q", ErrValidation, artifact.Kind)
	}
}

// renderHeader states what the document is and what it came from. Every
// artifact carries it so a file found on disk can be traced back to the exact
// approved version that produced it.
func renderHeader(b *strings.Builder, title string, plan *Plan, version *Version) {
	fmt.Fprintf(b, "# %s\n\n", title)
	fmt.Fprintf(b, "**Plan:** %s  \n", plan.ID)
	fmt.Fprintf(b, "**Version:** %d  \n", version.Number)
	fmt.Fprintf(b, "**Approved content hash:** `%s`\n\n", version.ContentHash)
	b.WriteString("_Generated by Ori from the approved plan. Edits here do not change the plan._\n\n")
}

func renderPRD(artifact ProposedArtifact, plan *Plan, version *Version) string {
	var b strings.Builder
	title := artifact.Title
	if strings.TrimSpace(title) == "" {
		title = version.Title
	}
	renderHeader(&b, title, plan, version)

	b.WriteString("## Objective\n\n")
	fmt.Fprintf(&b, "%s\n\n", orPlaceholder(version.Objective, "_No objective recorded._"))

	b.WriteString("## Original request\n\n")
	fmt.Fprintf(&b, "%s\n\n", orPlaceholder(plan.OriginalRequest, "_No request recorded._"))

	content := version.Content
	if strings.TrimSpace(content.Rationale) != "" {
		b.WriteString("## Rationale\n\n")
		fmt.Fprintf(&b, "%s\n\n", content.Rationale)
	}

	renderBulletSection(&b, "In scope", content.InScope)
	renderBulletSection(&b, "Non-goals", content.NonGoals)

	if len(content.Assumptions) > 0 {
		b.WriteString("## Assumptions\n\n")
		for _, assumption := range content.Assumptions {
			fmt.Fprintf(&b, "- %s\n", assumption.Statement)
		}
		b.WriteString("\n")
	}

	if len(content.Risks) > 0 {
		b.WriteString("## Risks\n\n")
		for _, risk := range content.Risks {
			if risk.Severity != "" {
				fmt.Fprintf(&b, "- **%s:** %s", risk.Severity, risk.Statement)
			} else {
				fmt.Fprintf(&b, "- %s", risk.Statement)
			}
			if strings.TrimSpace(risk.Mitigation) != "" {
				fmt.Fprintf(&b, " _(mitigation: %s)_", risk.Mitigation)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if len(content.Clarifications) > 0 {
		b.WriteString("## Clarifications\n\n")
		for _, question := range content.Clarifications {
			fmt.Fprintf(&b, "- **%s**\n", question.Prompt)
			switch question.Status {
			case ClarificationAnswered:
				fmt.Fprintf(&b, "  - %s\n", question.Answer)
			case ClarificationSkipped:
				b.WriteString("  - _Skipped._\n")
			default:
				b.WriteString("  - _Unanswered._\n")
			}
		}
		b.WriteString("\n")
	}

	if len(content.Validations) > 0 {
		b.WriteString("## Validation checkpoints\n\n")
		for _, checkpoint := range content.Validations {
			required := "optional"
			if checkpoint.Required {
				required = "required"
			}
			fmt.Fprintf(&b, "- %s (%s)", checkpoint.Title, required)
			if strings.TrimSpace(checkpoint.Expectation) != "" {
				fmt.Fprintf(&b, " — %s", checkpoint.Expectation)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Execution\n\n")
	fmt.Fprintf(&b, "- Mode: `%s`\n", content.Execution.Mode)
	for _, precondition := range content.Execution.Preconditions {
		fmt.Fprintf(&b, "- Enforced precondition: `%s`\n", precondition)
	}
	b.WriteString("\n")

	if strings.TrimSpace(content.Explanation) != "" {
		b.WriteString("## Notes\n\n")
		fmt.Fprintf(&b, "%s\n", content.Explanation)
	}

	return b.String()
}

func renderTaskList(artifact ProposedArtifact, plan *Plan, version *Version) string {
	var b strings.Builder
	title := artifact.Title
	if strings.TrimSpace(title) == "" {
		title = fmt.Sprintf("Tasks: %s", version.Title)
	}
	renderHeader(&b, title, plan, version)

	content := version.Content
	b.WriteString("## Relevant Files\n\n")
	fileCount := 0
	for _, source := range content.Sources {
		if source.Kind != SourceFile || strings.TrimSpace(source.Ref) == "" {
			continue
		}
		fileCount++
		description := strings.TrimSpace(source.Title)
		if description == "" {
			description = "Approved Plan source"
		}
		fmt.Fprintf(&b, "- `%s` - %s.\n", source.Ref, description)
	}
	if fileCount == 0 {
		b.WriteString("- Identify affected implementation and test files before editing.\n")
	}

	b.WriteString("\n### Notes\n\n")
	b.WriteString("- This checklist is the repository projection of an approved Ori Plan.\n")
	b.WriteString("- Workspace Tasks remain the execution source of truth; update the copied worktree checklist as implementation progresses.\n")
	b.WriteString("- Do not run `wt plan` again. This file is already a completed plan and is ready for `wt start`.\n\n")

	b.WriteString("## Instructions for Completing Tasks\n\n")
	b.WriteString("Complete tasks in dependency order. Check off each numbered sub-task only after its expected result is satisfied.\n\n")
	b.WriteString("## Tasks\n\n")
	if len(content.Groups) == 0 {
		b.WriteString("_This plan has no task groups._\n")
		return b.String()
	}

	for groupIndex, group := range content.Groups {
		groupNumber := groupIndex + 1
		fmt.Fprintf(&b, "- [ ] %d.0 %s\n", groupNumber, group.Title)
		if strings.TrimSpace(group.Outcome) != "" {
			fmt.Fprintf(&b, "  - Outcome: %s\n", group.Outcome)
		}
		if len(group.DependsOn) > 0 {
			fmt.Fprintf(&b, "  - Depends on: %s\n", strings.Join(group.DependsOn, ", "))
		}
		for itemIndex, item := range group.Items {
			fmt.Fprintf(&b, "  - [ ] %d.%d %s", groupNumber, itemIndex+1, item.Description)
			if item.Assignee != "" {
				fmt.Fprintf(&b, " — %s", item.Assignee)
			} else {
				b.WriteString(" — _unassigned_")
			}
			b.WriteString("\n")
			if strings.TrimSpace(item.Details) != "" {
				fmt.Fprintf(&b, "    - Details: %s\n", item.Details)
			}
			if strings.TrimSpace(item.ExpectedResult) != "" {
				fmt.Fprintf(&b, "    - Expected: %s\n", item.ExpectedResult)
			}
			if len(item.RequiredCapabilities) > 0 {
				fmt.Fprintf(&b, "    - Requires: %s\n", strings.Join(item.RequiredCapabilities, ", "))
			}
		}
	}

	return b.String()
}

func renderNote(artifact ProposedArtifact, plan *Plan, version *Version) string {
	var b strings.Builder
	title := artifact.Title
	if strings.TrimSpace(title) == "" {
		title = version.Title
	}
	renderHeader(&b, title, plan, version)

	if strings.TrimSpace(artifact.Description) != "" {
		fmt.Fprintf(&b, "%s\n\n", artifact.Description)
	}
	fmt.Fprintf(&b, "## Objective\n\n%s\n\n", orPlaceholder(version.Objective, "_No objective recorded._"))

	content := version.Content
	renderBulletSection(&b, "In scope", content.InScope)
	renderBulletSection(&b, "Non-goals", content.NonGoals)

	if len(content.Groups) > 0 {
		b.WriteString("## Planned work\n\n")
		for _, group := range content.Groups {
			fmt.Fprintf(&b, "- **%s** (%d task(s))\n", group.Title, len(group.Items))
		}
		b.WriteString("\n")
	}
	if strings.TrimSpace(content.Explanation) != "" {
		fmt.Fprintf(&b, "%s\n", content.Explanation)
	}
	return b.String()
}

func renderBulletSection(b *strings.Builder, heading string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s\n\n", heading)
	for _, value := range values {
		fmt.Fprintf(b, "- %s\n", value)
	}
	b.WriteString("\n")
}

func orPlaceholder(value, placeholder string) string {
	if strings.TrimSpace(value) == "" {
		return placeholder
	}
	return value
}
