// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/oriagent/ori-pluginapi"
)

// Compile-time interface checks
var _ pluginapi.PluginTool = (*MathTool)(nil)

// Optional interface checks (auto-detected from plugin.yaml)
var (
	_ pluginapi.VersionedTool       = (*MathTool)(nil)
	_ pluginapi.MetadataProvider    = (*MathTool)(nil)
	_ pluginapi.PluginCompatibility = (*MathTool)(nil)
)

//go:embed plugin.yaml
var configYAML string

// Params represents the parameters for this plugin
type Params struct {
	Operation string  `json:"operation"` // Operation to perform: add, subtract, multiply, divide
	A         float64 `json:"a"`         // First operand
	B         float64 `json:"b"`         // Second operand
}

// OperationHandler is a function that handles a specific operation
type OperationHandler func(ctx context.Context, t *MathTool, params *Params) (string, error)

// operationRegistry maps operation names to their handler functions
// Handler functions must be defined by you with the naming convention handle{PascalCase}
var operationRegistry = map[string]OperationHandler{
	"add":      handleAdd,
	"divide":   handleDivide,
	"multiply": handleMultiply,
	"subtract": handleSubtract,
}

// Execute dispatches to the appropriate operation handler
// This method is auto-generated from plugin.yaml operations
func (t *MathTool) Execute(ctx context.Context, params *Params) (string, error) {
	handler, ok := operationRegistry[params.Operation]
	if !ok {
		return "", fmt.Errorf("unknown operation: %s. Valid operations: add, divide, multiply, subtract", params.Operation)
	}
	return handler(ctx, t, params)
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *MathTool) Call(ctx context.Context, args string) (string, error) {
	var paramsMap map[string]interface{}

	// Unmarshal JSON arguments for validation
	if err := json.Unmarshal([]byte(args), &paramsMap); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	if err := pluginapi.ValidateToolParameters(t.Definition().Parameters, paramsMap); err != nil {
		return "", err
	}

	var params Params

	// Unmarshal JSON arguments into typed params
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Call the Execute method
	return t.Execute(ctx, &params)
}
