// Code generated by ori-plugin-gen. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/johnjallday/ori-agent/pluginapi"
)

// Compile-time interface check
var _ pluginapi.PluginTool = (*mathTool)(nil)

// MathParams represents the parameters for this plugin
type MathParams struct {
	Operation string  `json:"operation"` // Operation to perform: add, subtract, multiply, divide
	A         float64 `json:"a"`         // First operand
	B         float64 `json:"b"`         // Second operand
}

// Call implements the PluginTool interface
// This method is auto-generated from plugin.yaml
func (t *mathTool) Call(ctx context.Context, args string) (string, error) {
	var params MathParams

	// Unmarshal JSON arguments
	if err := json.Unmarshal([]byte(args), &params); err != nil {
		return "", fmt.Errorf("invalid arguments: %w", err)
	}

	// Validate required fields
	if params.Operation == "" {
		return "", fmt.Errorf("required field 'operation' is missing")
	}
	if params.A == 0 {
		return "", fmt.Errorf("required field 'a' is missing")
	}
	if params.B == 0 {
		return "", fmt.Errorf("required field 'b' is missing")
	}

	// Call the Execute method (implemented by you)
	return t.Execute(ctx, &params)
}
