package personalassistant

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/johnjallday/ori-agent/internal/followup"
	"github.com/johnjallday/ori-agent/internal/workspace"
)

const (
	// MaxAssignmentRows keeps one first-value mutation bounded below the
	// canonical-ref journal cap, leaving room for future metadata refs.
	MaxAssignmentRows = 50
)

// AssignmentRowType is the explicit user-selected meaning of one input row.
type AssignmentRowType string

const (
	AssignmentRowPriority        AssignmentRowType = "priority"
	AssignmentRowIOwe            AssignmentRowType = "i_owe"
	AssignmentRowWaitingOn       AssignmentRowType = "waiting_on"
	AssignmentRowFixedCommitment AssignmentRowType = "fixed_commitment"
)

// AssignmentRecordType is the canonical service an apply operation will use.
type AssignmentRecordType string

const (
	AssignmentRecordTicket   AssignmentRecordType = "ticket"
	AssignmentRecordFollowUp AssignmentRecordType = "follow_up"
)

// AssignmentInput is the bounded deterministic first-assignment submission.
type AssignmentInput struct {
	Rows []AssignmentInputRow `json:"rows"`
}

// AssignmentInputRow never asks a model to infer record type or action intent.
// Action is meaningful only for a fixed commitment: a non-empty action becomes
// a Ready ticket; no action becomes a needs_decision follow-up.
type AssignmentInputRow struct {
	Type         AssignmentRowType `json:"type"`
	Title        string            `json:"title"`
	Action       string            `json:"action,omitempty"`
	Detail       string            `json:"detail,omitempty"`
	Counterparty string            `json:"counterparty,omitempty"`
	Due          string            `json:"due,omitempty"`
}

// AssignmentPreviewItem is the immutable, exact apply plan returned to the
// browser. Category and State use canonical Ticket/follow-up values.
type AssignmentPreviewItem struct {
	ID                      string               `json:"id"`
	InputType               AssignmentRowType    `json:"input_type"`
	RecordType              AssignmentRecordType `json:"record_type"`
	Category                string               `json:"category"`
	State                   string               `json:"state"`
	Title                   string               `json:"title"`
	Detail                  string               `json:"detail,omitempty"`
	Counterparty            string               `json:"counterparty,omitempty"`
	Due                     string               `json:"due,omitempty"`
	AwaitingExecutionIntent bool                 `json:"awaiting_execution_intent,omitempty"`
}

// AssignmentPreview is one immutable normalized payload version.
type AssignmentPreview struct {
	PreviewID         string                  `json:"preview_id"`
	AssignmentVersion int64                   `json:"assignment_version"`
	PayloadHash       string                  `json:"payload_hash"`
	Items             []AssignmentPreviewItem `json:"items"`
	Count             int                     `json:"count"`
}

// BuildAssignmentPreview validates and deterministically maps explicit rows to
// canonical records. previewID is generated by the caller before persistence;
// item IDs derive from it and the normalized row position, so they cannot drift
// between response encoding and journal storage.
func BuildAssignmentPreview(previewID string, assignmentVersion int64, input AssignmentInput) (*AssignmentPreview, json.RawMessage, error) {
	previewID, err := validateOpaqueID("preview id", previewID, true)
	if err != nil {
		return nil, nil, fmt.Errorf("%w: %v", ErrValidation, err)
	}
	if assignmentVersion < 1 {
		return nil, nil, fmt.Errorf("%w: assignment version must be positive", ErrValidation)
	}
	if len(input.Rows) > MaxAssignmentRows {
		return nil, nil, fmt.Errorf("%w: at most %d assignment rows are allowed", ErrValidation, MaxAssignmentRows)
	}
	items := make([]AssignmentPreviewItem, 0, len(input.Rows))
	for rowIndex, row := range input.Rows {
		if assignmentRowEmpty(row) {
			continue
		}
		item, normalizeErr := normalizeAssignmentRow(previewID, len(items), row)
		if normalizeErr != nil {
			return nil, nil, fmt.Errorf("%w: row %d: %v", ErrValidation, rowIndex+1, normalizeErr)
		}
		items = append(items, item)
	}
	payload, err := json.Marshal(struct {
		PreviewID string                  `json:"preview_id"`
		Items     []AssignmentPreviewItem `json:"items"`
	}{PreviewID: previewID, Items: items})
	if err != nil {
		return nil, nil, fmt.Errorf("personal assistant: encode assignment preview: %w", err)
	}
	if len(payload) > MaxAssignmentJSONBytes {
		return nil, nil, fmt.Errorf("%w: assignment preview is too large", ErrValidation)
	}
	preview := &AssignmentPreview{
		PreviewID: previewID, AssignmentVersion: assignmentVersion,
		PayloadHash: PayloadHash(payload), Items: items, Count: len(items),
	}
	return preview, json.RawMessage(payload), nil
}

// NewAssignmentPreviewID creates a stable opaque preview identity.
func NewAssignmentPreviewID() string { return uuid.NewString() }

func assignmentRowEmpty(row AssignmentInputRow) bool {
	return strings.TrimSpace(string(row.Type)) == "" && strings.TrimSpace(row.Title) == "" &&
		strings.TrimSpace(row.Action) == "" && strings.TrimSpace(row.Detail) == "" &&
		strings.TrimSpace(row.Counterparty) == "" && strings.TrimSpace(row.Due) == ""
}

func normalizeAssignmentRow(previewID string, itemIndex int, row AssignmentInputRow) (AssignmentPreviewItem, error) {
	var item AssignmentPreviewItem
	item.InputType = AssignmentRowType(strings.ToLower(strings.TrimSpace(string(row.Type))))
	switch item.InputType {
	case AssignmentRowPriority, AssignmentRowIOwe, AssignmentRowWaitingOn, AssignmentRowFixedCommitment:
	default:
		return item, fmt.Errorf("unsupported row type %q", row.Type)
	}

	title, err := normalizeAssignmentText("title", row.Title, followup.MaxTitleLen, true, true)
	if err != nil {
		return item, err
	}
	detail, err := normalizeAssignmentText("detail", row.Detail, followup.MaxDetailLen, false, false)
	if err != nil {
		return item, err
	}
	counterparty, err := normalizeAssignmentText("counterparty", row.Counterparty, followup.MaxTitleLen, false, true)
	if err != nil {
		return item, err
	}
	action, err := normalizeAssignmentText("action", row.Action, followup.MaxTitleLen, false, true)
	if err != nil {
		return item, err
	}
	due, err := normalizeAssignmentDue(row.Due)
	if err != nil {
		return item, err
	}

	item.ID = PayloadHash([]byte(fmt.Sprintf("%s:%d", previewID, itemIndex)))[:24]
	item.Title = title
	item.Detail = detail
	item.Counterparty = counterparty
	item.Due = due

	switch item.InputType {
	case AssignmentRowPriority:
		if action != "" {
			return item, errors.New("action is supported only for fixed commitments")
		}
		item.RecordType = AssignmentRecordTicket
		item.Category = "today_priority"
		item.State = string(workspace.TicketStateReady)
		item.AwaitingExecutionIntent = true
	case AssignmentRowIOwe:
		if action != "" {
			return item, errors.New("action is supported only for fixed commitments")
		}
		item.RecordType = AssignmentRecordFollowUp
		item.Category = string(followup.CategoryIOwe)
		item.State = string(followup.StatusActive)
	case AssignmentRowWaitingOn:
		if action != "" {
			return item, errors.New("action is supported only for fixed commitments")
		}
		item.RecordType = AssignmentRecordFollowUp
		item.Category = string(followup.CategoryWaitingOn)
		item.State = string(followup.StatusActive)
	case AssignmentRowFixedCommitment:
		if action == "" {
			item.RecordType = AssignmentRecordFollowUp
			item.Category = string(followup.CategoryNeedsDecision)
			item.State = string(followup.StatusActive)
			break
		}
		item.RecordType = AssignmentRecordTicket
		item.Category = "fixed_commitment_action"
		item.State = string(workspace.TicketStateReady)
		item.AwaitingExecutionIntent = true
		item.Title = action
		context := "Fixed commitment: " + title
		if detail != "" {
			context += "\n\n" + detail
		}
		item.Detail = context
	}
	return item, nil
}

func normalizeAssignmentText(label, raw string, maximum int, required, singleLine bool) (string, error) {
	value, err := validateText(label, raw, maximum, required)
	if err != nil {
		return "", err
	}
	if singleLine && strings.ContainsAny(value, "\r\n") {
		return "", fmt.Errorf("%s must be one line", label)
	}
	return value, nil
}

func normalizeAssignmentDue(raw string) (string, error) {
	value := strings.TrimSpace(raw)
	if value == "" {
		return "", nil
	}
	if date, err := time.Parse("2006-01-02", value); err == nil {
		return date.Format("2006-01-02"), nil
	}
	instant, err := time.Parse(time.RFC3339, value)
	if err != nil {
		return "", errors.New("due must be YYYY-MM-DD or RFC3339")
	}
	return instant.Format(time.RFC3339), nil
}
